// Generated by esidl (r1745).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#ifndef ORG_W3C_DOM_BOOTSTRAP_CSSCOLORCOMPONENTVALUEIMP_H_INCLUDED
#define ORG_W3C_DOM_BOOTSTRAP_CSSCOLORCOMPONENTVALUEIMP_H_INCLUDED

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <org/w3c/dom/css/CSSColorComponentValue.h>

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{
class CSSColorComponentValueImp : public ObjectMixin<CSSColorComponentValueImp>
{
public:
    // CSSColorComponentValue
    short getRed() __attribute__((weak));
    void setRed(short red) __attribute__((weak));
    short getGreen() __attribute__((weak));
    void setGreen(short green) __attribute__((weak));
    short getBlue() __attribute__((weak));
    void setBlue(short blue) __attribute__((weak));
    float getAlpha() __attribute__((weak));
    void setAlpha(float alpha) __attribute__((weak));
    // Object
    virtual Any message_(uint32_t selector, const char* id, int argc, Any* argv)
    {
        return css::CSSColorComponentValue::dispatch(this, selector, id, argc, argv);
    }
    static const char* const getMetaData()
    {
        return css::CSSColorComponentValue::getMetaData();
    }
};

}
}
}
}

#endif  // ORG_W3C_DOM_BOOTSTRAP_CSSCOLORCOMPONENTVALUEIMP_H_INCLUDED
