// Generated by esidl (r1745).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "CSSColorComponentValueImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

short CSSColorComponentValueImp::getRed()
{
    // TODO: implement me!
    return 0;
}

void CSSColorComponentValueImp::setRed(short red)
{
    // TODO: implement me!
}

short CSSColorComponentValueImp::getGreen()
{
    // TODO: implement me!
    return 0;
}

void CSSColorComponentValueImp::setGreen(short green)
{
    // TODO: implement me!
}

short CSSColorComponentValueImp::getBlue()
{
    // TODO: implement me!
    return 0;
}

void CSSColorComponentValueImp::setBlue(short blue)
{
    // TODO: implement me!
}

float CSSColorComponentValueImp::getAlpha()
{
    // TODO: implement me!
    return 0;
}

void CSSColorComponentValueImp::setAlpha(float alpha)
{
    // TODO: implement me!
}

}
}
}
}
