// Generated by esidl (r1745).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#ifndef ORG_W3C_DOM_BOOTSTRAP_CSSKEYWORDCOMPONENTVALUEIMP_H_INCLUDED
#define ORG_W3C_DOM_BOOTSTRAP_CSSKEYWORDCOMPONENTVALUEIMP_H_INCLUDED

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <org/w3c/dom/css/CSSKeywordComponentValue.h>

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{
class CSSKeywordComponentValueImp : public ObjectMixin<CSSKeywordComponentValueImp>
{
public:
    // CSSKeywordComponentValue
    std::u16string getKeyword() __attribute__((weak));
    void setKeyword(std::u16string keyword) __attribute__((weak));
    // Object
    virtual Any message_(uint32_t selector, const char* id, int argc, Any* argv)
    {
        return css::CSSKeywordComponentValue::dispatch(this, selector, id, argc, argv);
    }
    static const char* const getMetaData()
    {
        return css::CSSKeywordComponentValue::getMetaData();
    }
};

}
}
}
}

#endif  // ORG_W3C_DOM_BOOTSTRAP_CSSKEYWORDCOMPONENTVALUEIMP_H_INCLUDED
