// Generated by esidl (r1745).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "CSSNamespaceRuleImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

std::u16string CSSNamespaceRuleImp::getNamespaceURI()
{
    // TODO: implement me!
    return u"";
}

Nullable<std::u16string> CSSNamespaceRuleImp::getPrefix()
{
    // TODO: implement me!
    return u"";
}

}
}
}
}
