// Generated by esidl (r1745).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#ifndef ORG_W3C_DOM_BOOTSTRAP_CSSPRIMITIVEVALUEIMP_H_INCLUDED
#define ORG_W3C_DOM_BOOTSTRAP_CSSPRIMITIVEVALUEIMP_H_INCLUDED

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <org/w3c/dom/css/CSSPrimitiveValue.h>
#include "CSSValueImp.h"

#include <org/w3c/dom/css/CSSValue.h>
#include <org/w3c/dom/css/RGBColor.h>
#include <org/w3c/dom/css/Rect.h>
#include <org/w3c/dom/css/Counter.h>
#include <org/w3c/dom/DOMException.h>

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{
class CSSPrimitiveValueImp : public ObjectMixin<CSSPrimitiveValueImp, CSSValueImp>
{
public:
    // CSSPrimitiveValue
    unsigned short getPrimitiveType() __attribute__((weak));
    void setFloatValue(unsigned short unitType, float floatValue) throw(DOMException) __attribute__((weak));
    float getFloatValue(unsigned short unitType) throw(DOMException) __attribute__((weak));
    void setStringValue(unsigned short stringType, std::u16string stringValue) throw(DOMException) __attribute__((weak));
    std::u16string getStringValue() throw(DOMException) __attribute__((weak));
    css::Counter getCounterValue() throw(DOMException) __attribute__((weak));
    css::Rect getRectValue() throw(DOMException) __attribute__((weak));
    css::RGBColor getRGBColorValue() throw(DOMException) __attribute__((weak));
    // Object
    virtual Any message_(uint32_t selector, const char* id, int argc, Any* argv)
    {
        return css::CSSPrimitiveValue::dispatch(this, selector, id, argc, argv);
    }
    static const char* const getMetaData()
    {
        return css::CSSPrimitiveValue::getMetaData();
    }
};

}
}
}
}

#endif  // ORG_W3C_DOM_BOOTSTRAP_CSSPRIMITIVEVALUEIMP_H_INCLUDED
