// Generated by esidl (r1745).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "CSSPropertyValueListImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

ObjectArray<css::CSSValue> CSSPropertyValueListImp::getList()
{
    // TODO: implement me!
    return static_cast<Object*>(0);
}

}
}
}
}
