// Generated by esidl (r1745).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "CSSStringComponentValueImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

std::u16string CSSStringComponentValueImp::getString()
{
    // TODO: implement me!
    return u"";
}

void CSSStringComponentValueImp::setString(std::u16string string)
{
    // TODO: implement me!
}

}
}
}
}
