// Generated by esidl (r1745).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#ifndef ORG_W3C_DOM_BOOTSTRAP_CSSVALUELISTIMP_H_INCLUDED
#define ORG_W3C_DOM_BOOTSTRAP_CSSVALUELISTIMP_H_INCLUDED

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <org/w3c/dom/css/CSSValueList.h>
#include "CSSValueImp.h"

#include <org/w3c/dom/css/CSSValue.h>

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{
class CSSValueListImp : public ObjectMixin<CSSValueListImp, CSSValueImp>
{
public:
    // CSSValueList
    unsigned int getLength();
    css::CSSValue item(unsigned int index);
    // Object
    virtual Any message_(uint32_t selector, const char* id, int argc, Any* argv)
    {
        return css::CSSValueList::dispatch(this, selector, id, argc, argv);
    }
    static const char* const getMetaData()
    {
        return css::CSSValueList::getMetaData();
    }
};

}
}
}
}

#endif  // ORG_W3C_DOM_BOOTSTRAP_CSSVALUELISTIMP_H_INCLUDED
