// Generated by esidl (r1745).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "RectImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

css::CSSPrimitiveValue RectImp::getTop()
{
    // TODO: implement me!
    return static_cast<Object*>(0);
}

css::CSSPrimitiveValue RectImp::getRight()
{
    // TODO: implement me!
    return static_cast<Object*>(0);
}

css::CSSPrimitiveValue RectImp::getBottom()
{
    // TODO: implement me!
    return static_cast<Object*>(0);
}

css::CSSPrimitiveValue RectImp::getLeft()
{
    // TODO: implement me!
    return static_cast<Object*>(0);
}

}
}
}
}
