// Generated by esidl (r2593).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#ifndef ORG_W3C_DOM_BOOTSTRAP_XBLIMPLEMENTATIONLISTIMP_H_INCLUDED
#define ORG_W3C_DOM_BOOTSTRAP_XBLIMPLEMENTATIONLISTIMP_H_INCLUDED

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <org/w3c/dom/xbl2/XBLImplementationList.h>

#include <org/w3c/dom/xbl2/XBLImplementation.h>

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{
class XBLImplementationListImp : public ObjectMixin<XBLImplementationListImp>
{
public:
    // XBLImplementationList
    xbl2::XBLImplementation item(unsigned int index);
    unsigned int getLength();
    // Object
    virtual Any message_(uint32_t selector, const char* id, int argc, Any* argv)
    {
        return xbl2::XBLImplementationList::dispatch(this, selector, id, argc, argv);
    }
    static const char* const getMetaData()
    {
        return xbl2::XBLImplementationList::getMetaData();
    }
};

}
}
}
}

#endif  // ORG_W3C_DOM_BOOTSTRAP_XBLIMPLEMENTATIONLISTIMP_H_INCLUDED
