// Generated by esidl 0.3.0.
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "AudioTrackListImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

unsigned int AudioTrackListImp::getLength()
{
    // TODO: implement me!
    return 0;
}

html::AudioTrack AudioTrackListImp::getElement(unsigned int index)
{
    // TODO: implement me!
    return nullptr;
}

html::AudioTrack AudioTrackListImp::getTrackById(const std::u16string& id)
{
    // TODO: implement me!
    return nullptr;
}

events::EventHandlerNonNull AudioTrackListImp::getOnchange()
{
    // TODO: implement me!
    return nullptr;
}

void AudioTrackListImp::setOnchange(events::EventHandlerNonNull onchange)
{
    // TODO: implement me!
}

events::EventHandlerNonNull AudioTrackListImp::getOnaddtrack()
{
    // TODO: implement me!
    return nullptr;
}

void AudioTrackListImp::setOnaddtrack(events::EventHandlerNonNull onaddtrack)
{
    // TODO: implement me!
}

events::EventHandlerNonNull AudioTrackListImp::getOnremovetrack()
{
    // TODO: implement me!
    return nullptr;
}

void AudioTrackListImp::setOnremovetrack(events::EventHandlerNonNull onremovetrack)
{
    // TODO: implement me!
}

}
}
}
}
