// Generated by esidl 0.3.0.
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "CanvasPathMethodsImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

void CanvasPathMethodsImp::closePath()
{
    // TODO: implement me!
}

void CanvasPathMethodsImp::moveTo(double x, double y)
{
    // TODO: implement me!
}

void CanvasPathMethodsImp::lineTo(double x, double y)
{
    // TODO: implement me!
}

void CanvasPathMethodsImp::quadraticCurveTo(double cpx, double cpy, double x, double y)
{
    // TODO: implement me!
}

void CanvasPathMethodsImp::bezierCurveTo(double cp1x, double cp1y, double cp2x, double cp2y, double x, double y)
{
    // TODO: implement me!
}

void CanvasPathMethodsImp::arcTo(double x1, double y1, double x2, double y2, double radius)
{
    // TODO: implement me!
}

void CanvasPathMethodsImp::rect(double x, double y, double w, double h)
{
    // TODO: implement me!
}

void CanvasPathMethodsImp::arc(double x, double y, double radius, double startAngle, double endAngle)
{
    // TODO: implement me!
}

void CanvasPathMethodsImp::arc(double x, double y, double radius, double startAngle, double endAngle, bool anticlockwise)
{
    // TODO: implement me!
}

void CanvasPathMethodsImp::ellipse(double x, double y, double radiusX, double radiusY, double rotation, double startAngle, double endAngle, bool anticlockwise)
{
    // TODO: implement me!
}

}
}
}
}
