// Generated by esidl (r1752).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#ifndef ORG_W3C_DOM_BOOTSTRAP_CANVASPIXELARRAYIMP_H_INCLUDED
#define ORG_W3C_DOM_BOOTSTRAP_CANVASPIXELARRAYIMP_H_INCLUDED

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <org/w3c/dom/html/CanvasPixelArray.h>

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{
class CanvasPixelArrayImp : public ObjectMixin<CanvasPixelArrayImp>
{
public:
    // CanvasPixelArray
    unsigned int getLength();
    unsigned char getElement(unsigned int index);
    void setElement(unsigned int index, unsigned char value);
    // Object
    virtual Any message_(uint32_t selector, const char* id, int argc, Any* argv)
    {
        return html::CanvasPixelArray::dispatch(this, selector, id, argc, argv);
    }
    static const char* const getMetaData()
    {
        return html::CanvasPixelArray::getMetaData();
    }
};

}
}
}
}

#endif  // ORG_W3C_DOM_BOOTSTRAP_CANVASPIXELARRAYIMP_H_INCLUDED
