// Generated by esidl 0.3.0.
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "CanvasDrawingStylesImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

double CanvasDrawingStylesImp::getLineWidth()
{
    // TODO: implement me!
    return 0;
}

void CanvasDrawingStylesImp::setLineWidth(double lineWidth)
{
    // TODO: implement me!
}

std::u16string CanvasDrawingStylesImp::getLineCap()
{
    // TODO: implement me!
    return u"";
}

void CanvasDrawingStylesImp::setLineCap(const std::u16string& lineCap)
{
    // TODO: implement me!
}

std::u16string CanvasDrawingStylesImp::getLineJoin()
{
    // TODO: implement me!
    return u"";
}

void CanvasDrawingStylesImp::setLineJoin(const std::u16string& lineJoin)
{
    // TODO: implement me!
}

double CanvasDrawingStylesImp::getMiterLimit()
{
    // TODO: implement me!
    return 0;
}

void CanvasDrawingStylesImp::setMiterLimit(double miterLimit)
{
    // TODO: implement me!
}

void CanvasDrawingStylesImp::setLineDash(Sequence<double> segments)
{
    // TODO: implement me!
}

Sequence<double> CanvasDrawingStylesImp::getLineDash()
{
    // TODO: implement me!
    return Sequence<double>();
}

double CanvasDrawingStylesImp::getLineDashOffset()
{
    // TODO: implement me!
    return 0;
}

void CanvasDrawingStylesImp::setLineDashOffset(double lineDashOffset)
{
    // TODO: implement me!
}

std::u16string CanvasDrawingStylesImp::getFont()
{
    // TODO: implement me!
    return u"";
}

void CanvasDrawingStylesImp::setFont(const std::u16string& font)
{
    // TODO: implement me!
}

std::u16string CanvasDrawingStylesImp::getTextAlign()
{
    // TODO: implement me!
    return u"";
}

void CanvasDrawingStylesImp::setTextAlign(const std::u16string& textAlign)
{
    // TODO: implement me!
}

std::u16string CanvasDrawingStylesImp::getTextBaseline()
{
    // TODO: implement me!
    return u"";
}

void CanvasDrawingStylesImp::setTextBaseline(const std::u16string& textBaseline)
{
    // TODO: implement me!
}

}
}
}
}
