// Generated by esidl 0.3.0.
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "DataTransferItemListImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

unsigned int DataTransferItemListImp::getLength()
{
    // TODO: implement me!
    return 0;
}

html::DataTransferItem DataTransferItemListImp::getElement(unsigned int index)
{
    // TODO: implement me!
    return nullptr;
}

void DataTransferItemListImp::deleteElement(unsigned int index)
{
    // TODO: implement me!
}

void DataTransferItemListImp::clear()
{
    // TODO: implement me!
}

html::DataTransferItem DataTransferItemListImp::add(const std::u16string& data, const std::u16string& type)
{
    // TODO: implement me!
    return nullptr;
}

html::DataTransferItem DataTransferItemListImp::add(file::File data)
{
    // TODO: implement me!
    return nullptr;
}

}
}
}
}
