// Generated by esidl (r1745).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "HTMLParagraphElementImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

std::u16string HTMLParagraphElementImp::getAlign()
{
    // TODO: implement me!
    return u"";
}

void HTMLParagraphElementImp::setAlign(std::u16string align)
{
    // TODO: implement me!
}

}
}
}
}
