// Generated by esidl 0.2.1.
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "HTMLAppletElementImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

std::u16string HTMLAppletElementImp::getAlign()
{
    // TODO: implement me!
    return u"";
}

void HTMLAppletElementImp::setAlign(const std::u16string& align)
{
    // TODO: implement me!
}

std::u16string HTMLAppletElementImp::getAlt()
{
    // TODO: implement me!
    return u"";
}

void HTMLAppletElementImp::setAlt(const std::u16string& alt)
{
    // TODO: implement me!
}

std::u16string HTMLAppletElementImp::getArchive()
{
    // TODO: implement me!
    return u"";
}

void HTMLAppletElementImp::setArchive(const std::u16string& archive)
{
    // TODO: implement me!
}

std::u16string HTMLAppletElementImp::getCode()
{
    // TODO: implement me!
    return u"";
}

void HTMLAppletElementImp::setCode(const std::u16string& code)
{
    // TODO: implement me!
}

std::u16string HTMLAppletElementImp::getCodeBase()
{
    // TODO: implement me!
    return u"";
}

void HTMLAppletElementImp::setCodeBase(const std::u16string& codeBase)
{
    // TODO: implement me!
}

std::u16string HTMLAppletElementImp::getHeight()
{
    // TODO: implement me!
    return u"";
}

void HTMLAppletElementImp::setHeight(const std::u16string& height)
{
    // TODO: implement me!
}

unsigned int HTMLAppletElementImp::getHspace()
{
    // TODO: implement me!
    return 0;
}

void HTMLAppletElementImp::setHspace(unsigned int hspace)
{
    // TODO: implement me!
}

std::u16string HTMLAppletElementImp::getName()
{
    // TODO: implement me!
    return u"";
}

void HTMLAppletElementImp::setName(const std::u16string& name)
{
    // TODO: implement me!
}

std::u16string HTMLAppletElementImp::getObject()
{
    // TODO: implement me!
    return u"";
}

void HTMLAppletElementImp::setObject(const std::u16string& object)
{
    // TODO: implement me!
}

unsigned int HTMLAppletElementImp::getVspace()
{
    // TODO: implement me!
    return 0;
}

void HTMLAppletElementImp::setVspace(unsigned int vspace)
{
    // TODO: implement me!
}

std::u16string HTMLAppletElementImp::getWidth()
{
    // TODO: implement me!
    return u"";
}

void HTMLAppletElementImp::setWidth(const std::u16string& width)
{
    // TODO: implement me!
}

}
}
}
}
