// Generated by esidl (r2593).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "HTMLTemplateElementImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

Element HTMLTemplateElementImp::getElementById(std::u16string elementId)
{
    // TODO: implement me!
    return static_cast<Object*>(0);
}

}
}
}
}
