// Generated by esidl (r1745).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "HTMLPropertiesCollectionImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

html::PropertyNodeList HTMLPropertiesCollectionImp::namedItem(std::u16string name)
{
    // TODO: implement me!
    return static_cast<Object*>(0);
}

DOMStringList HTMLPropertiesCollectionImp::getNames()
{
    // TODO: implement me!
    return static_cast<Object*>(0);
}

}
}
}
}
