// Generated by esidl 0.3.0.
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "HTMLDialogElementImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

bool HTMLDialogElementImp::getOpen()
{
    // TODO: implement me!
    return 0;
}

void HTMLDialogElementImp::setOpen(bool open)
{
    // TODO: implement me!
}

std::u16string HTMLDialogElementImp::getReturnValue()
{
    // TODO: implement me!
    return u"";
}

void HTMLDialogElementImp::setReturnValue(const std::u16string& returnValue)
{
    // TODO: implement me!
}

void HTMLDialogElementImp::show()
{
    // TODO: implement me!
}

void HTMLDialogElementImp::show(Any anchor)
{
    // TODO: implement me!
}

void HTMLDialogElementImp::showModal()
{
    // TODO: implement me!
}

void HTMLDialogElementImp::showModal(Any anchor)
{
    // TODO: implement me!
}

void HTMLDialogElementImp::close()
{
    // TODO: implement me!
}

void HTMLDialogElementImp::close(const std::u16string& returnValue)
{
    // TODO: implement me!
}

}
}
}
}
