// Generated by esidl 0.3.0.
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "HTMLProgressElementImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

double HTMLProgressElementImp::getValue()
{
    // TODO: implement me!
    return 0;
}

void HTMLProgressElementImp::setValue(double value)
{
    // TODO: implement me!
}

double HTMLProgressElementImp::getMax()
{
    // TODO: implement me!
    return 0;
}

void HTMLProgressElementImp::setMax(double max)
{
    // TODO: implement me!
}

double HTMLProgressElementImp::getPosition()
{
    // TODO: implement me!
    return 0;
}

NodeList HTMLProgressElementImp::getLabels()
{
    // TODO: implement me!
    return static_cast<Object*>(0);
}

}
}
}
}
