// Generated by esidl (r1745).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "HTMLModElementImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

std::u16string HTMLModElementImp::getCite()
{
    // TODO: implement me!
    return u"";
}

void HTMLModElementImp::setCite(std::u16string cite)
{
    // TODO: implement me!
}

std::u16string HTMLModElementImp::getDateTime()
{
    // TODO: implement me!
    return u"";
}

void HTMLModElementImp::setDateTime(std::u16string dateTime)
{
    // TODO: implement me!
}

}
}
}
}
