// Generated by esidl 0.3.0.
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "HTMLSourceElementImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

std::u16string HTMLSourceElementImp::getSrc()
{
    // TODO: implement me!
    return u"";
}

void HTMLSourceElementImp::setSrc(const std::u16string& src)
{
    // TODO: implement me!
}

std::u16string HTMLSourceElementImp::getType()
{
    // TODO: implement me!
    return u"";
}

void HTMLSourceElementImp::setType(const std::u16string& type)
{
    // TODO: implement me!
}

std::u16string HTMLSourceElementImp::getMedia()
{
    // TODO: implement me!
    return u"";
}

void HTMLSourceElementImp::setMedia(const std::u16string& media)
{
    // TODO: implement me!
}

}
}
}
}
