// Generated by esidl (r1745).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#ifndef ORG_W3C_DOM_BOOTSTRAP_HTMLOUTPUTELEMENTIMP_H_INCLUDED
#define ORG_W3C_DOM_BOOTSTRAP_HTMLOUTPUTELEMENTIMP_H_INCLUDED

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <org/w3c/dom/html/HTMLOutputElement.h>
#include "HTMLElementImp.h"

#include <org/w3c/dom/html/HTMLElement.h>
#include <org/w3c/dom/NodeList.h>
#include <org/w3c/dom/DOMSettableTokenList.h>
#include <org/w3c/dom/html/HTMLFormElement.h>
#include <org/w3c/dom/html/ValidityState.h>

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{
class HTMLOutputElementImp : public ObjectMixin<HTMLOutputElementImp, HTMLElementImp>
{
public:
    // HTMLOutputElement
    DOMSettableTokenList getHtmlFor();
    void setHtmlFor(std::u16string htmlFor);
    html::HTMLFormElement getForm();
    std::u16string getName();
    void setName(std::u16string name);
    std::u16string getType();
    std::u16string getDefaultValue();
    void setDefaultValue(std::u16string defaultValue);
    std::u16string getValue();
    void setValue(std::u16string value);
    bool getWillValidate();
    html::ValidityState getValidity();
    std::u16string getValidationMessage();
    bool checkValidity();
    void setCustomValidity(std::u16string error);
    NodeList getLabels();
    // Object
    virtual Any message_(uint32_t selector, const char* id, int argc, Any* argv)
    {
        return html::HTMLOutputElement::dispatch(this, selector, id, argc, argv);
    }
    static const char* const getMetaData()
    {
        return html::HTMLOutputElement::getMetaData();
    }
    HTMLOutputElementImp(DocumentImp* ownerDocument) :
        ObjectMixin(ownerDocument, u"output") {
    }
    HTMLOutputElementImp(HTMLOutputElementImp* org, bool deep) :
        ObjectMixin(org, deep) {
    }
};

}
}
}
}

#endif  // ORG_W3C_DOM_BOOTSTRAP_HTMLOUTPUTELEMENTIMP_H_INCLUDED
