// Generated by esidl 0.3.0.
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "HTMLDirectoryElementImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

bool HTMLDirectoryElementImp::getCompact()
{
    // TODO: implement me!
    return 0;
}

void HTMLDirectoryElementImp::setCompact(bool compact)
{
    // TODO: implement me!
}

}
}
}
}
