// Generated by esidl 0.3.0.
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#ifndef ORG_W3C_DOM_BOOTSTRAP_HTMLFRAMEELEMENTIMP_H_INCLUDED
#define ORG_W3C_DOM_BOOTSTRAP_HTMLFRAMEELEMENTIMP_H_INCLUDED

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <org/w3c/dom/html/HTMLFrameElement.h>
#include "HTMLElementImp.h"

#include <org/w3c/dom/Document.h>
#include <org/w3c/dom/html/HTMLElement.h>
#include <org/w3c/dom/html/Window.h>

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{
class HTMLFrameElementImp : public ObjectMixin<HTMLFrameElementImp, HTMLElementImp>
{
public:
    // HTMLFrameElement
    std::u16string getName();
    void setName(const std::u16string& name);
    std::u16string getScrolling();
    void setScrolling(const std::u16string& scrolling);
    std::u16string getSrc();
    void setSrc(const std::u16string& src);
    std::u16string getFrameBorder();
    void setFrameBorder(const std::u16string& frameBorder);
    std::u16string getLongDesc();
    void setLongDesc(const std::u16string& longDesc);
    bool getNoResize();
    void setNoResize(bool noResize);
    Document getContentDocument();
    html::Window getContentWindow();
    std::u16string getMarginHeight();
    void setMarginHeight(const std::u16string& marginHeight);
    std::u16string getMarginWidth();
    void setMarginWidth(const std::u16string& marginWidth);
    // Object
    virtual Any message_(uint32_t selector, const char* id, int argc, Any* argv)
    {
        return html::HTMLFrameElement::dispatch(this, selector, id, argc, argv);
    }
    static const char* const getMetaData()
    {
        return html::HTMLFrameElement::getMetaData();
    }
};

}
}
}
}

#endif  // ORG_W3C_DOM_BOOTSTRAP_HTMLFRAMEELEMENTIMP_H_INCLUDED
