// Generated by esidl 0.2.1.
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "HTMLAllCollectionImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

Object HTMLAllCollectionImp::namedItem(const std::u16string& name)
{
    // TODO: implement me!
    return static_cast<Object*>(0);
}

html::HTMLAllCollection HTMLAllCollectionImp::tags(const std::u16string& tagName)
{
    // TODO: implement me!
    return static_cast<Object*>(0);
}

}
}
}
}
