// Generated by esidl (r1745).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "HTMLUListElementImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

bool HTMLUListElementImp::getCompact()
{
    // TODO: implement me!
    return 0;
}

void HTMLUListElementImp::setCompact(bool compact)
{
    // TODO: implement me!
}

std::u16string HTMLUListElementImp::getType()
{
    // TODO: implement me!
    return u"";
}

void HTMLUListElementImp::setType(std::u16string type)
{
    // TODO: implement me!
}

}
}
}
}
