// Generated by esidl (r1745).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "HTMLLabelElementImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

html::HTMLFormElement HTMLLabelElementImp::getForm()
{
    // TODO: implement me!
    return static_cast<Object*>(0);
}

std::u16string HTMLLabelElementImp::getHtmlFor()
{
    // TODO: implement me!
    return u"";
}

void HTMLLabelElementImp::setHtmlFor(std::u16string htmlFor)
{
    // TODO: implement me!
}

html::HTMLElement HTMLLabelElementImp::getControl()
{
    // TODO: implement me!
    return static_cast<Object*>(0);
}

}
}
}
}
