// Generated by esidl 0.3.0.
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#ifndef ORG_W3C_DOM_BOOTSTRAP_HTMLTRACKELEMENTIMP_H_INCLUDED
#define ORG_W3C_DOM_BOOTSTRAP_HTMLTRACKELEMENTIMP_H_INCLUDED

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <org/w3c/dom/html/HTMLTrackElement.h>
#include "HTMLElementImp.h"

#include <org/w3c/dom/html/HTMLElement.h>
#include <org/w3c/dom/html/TextTrack.h>

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{
class HTMLTrackElementImp : public ObjectMixin<HTMLTrackElementImp, HTMLElementImp>
{
public:
    // HTMLTrackElement
    std::u16string getKind();
    void setKind(const std::u16string& kind);
    std::u16string getSrc();
    void setSrc(const std::u16string& src);
    std::u16string getSrclang();
    void setSrclang(const std::u16string& srclang);
    std::u16string getLabel();
    void setLabel(const std::u16string& label);
    bool getDefault();
    void setDefault(bool _default);
    unsigned short getReadyState();
    html::TextTrack getTrack();
    // Object
    virtual Any message_(uint32_t selector, const char* id, int argc, Any* argv)
    {
        return html::HTMLTrackElement::dispatch(this, selector, id, argc, argv);
    }
    static const char* const getMetaData()
    {
        return html::HTMLTrackElement::getMetaData();
    }
};

}
}
}
}

#endif  // ORG_W3C_DOM_BOOTSTRAP_HTMLTRACKELEMENTIMP_H_INCLUDED
