// Generated by esidl 0.3.0.
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "ImageDataImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

unsigned int ImageDataImp::getWidth()
{
    // TODO: implement me!
    return 0;
}

unsigned int ImageDataImp::getHeight()
{
    // TODO: implement me!
    return 0;
}

Uint8ClampedArray ImageDataImp::getData()
{
    // TODO: implement me!
    return static_cast<Object*>(0);
}

}
}
}
}
