// Generated by esidl 0.3.2.
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "MediaQueryListListenerImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

void MediaQueryListListenerImp::operator() (html::MediaQueryList list)
{
    // TODO: implement me!
}

}
}
}
}
