// Generated by esidl 0.3.0.
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "MessagePortImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

void MessagePortImp::postMessage(Any message)
{
    // TODO: implement me!
}

void MessagePortImp::postMessage(Any message, Sequence<html::Transferable> transfer)
{
    // TODO: implement me!
}

void MessagePortImp::start()
{
    // TODO: implement me!
}

void MessagePortImp::close()
{
    // TODO: implement me!
}

events::EventHandlerNonNull MessagePortImp::getOnmessage()
{
    // TODO: implement me!
    return static_cast<Object*>(0);
}

void MessagePortImp::setOnmessage(events::EventHandlerNonNull onmessage)
{
    // TODO: implement me!
}

}
}
}
}
