// Generated by esidl 0.3.0.
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "TextMetricsImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

double TextMetricsImp::getWidth()
{
    // TODO: implement me!
    return 0;
}

double TextMetricsImp::getActualBoundingBoxLeft()
{
    // TODO: implement me!
    return 0;
}

double TextMetricsImp::getActualBoundingBoxRight()
{
    // TODO: implement me!
    return 0;
}

double TextMetricsImp::getFontBoundingBoxAscent()
{
    // TODO: implement me!
    return 0;
}

double TextMetricsImp::getFontBoundingBoxDescent()
{
    // TODO: implement me!
    return 0;
}

double TextMetricsImp::getActualBoundingBoxAscent()
{
    // TODO: implement me!
    return 0;
}

double TextMetricsImp::getActualBoundingBoxDescent()
{
    // TODO: implement me!
    return 0;
}

double TextMetricsImp::getEmHeightAscent()
{
    // TODO: implement me!
    return 0;
}

double TextMetricsImp::getEmHeightDescent()
{
    // TODO: implement me!
    return 0;
}

double TextMetricsImp::getHangingBaseline()
{
    // TODO: implement me!
    return 0;
}

double TextMetricsImp::getAlphabeticBaseline()
{
    // TODO: implement me!
    return 0;
}

double TextMetricsImp::getIdeographicBaseline()
{
    // TODO: implement me!
    return 0;
}

}
}
}
}
