// Generated by esidl 0.3.0.
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "TextTrackListImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

unsigned int TextTrackListImp::getLength()
{
    // TODO: implement me!
    return 0;
}

html::TextTrack TextTrackListImp::getElement(unsigned int index)
{
    // TODO: implement me!
    return static_cast<Object*>(0);
}

events::EventHandlerNonNull TextTrackListImp::getOnaddtrack()
{
    // TODO: implement me!
    return static_cast<Object*>(0);
}

void TextTrackListImp::setOnaddtrack(events::EventHandlerNonNull onaddtrack)
{
    // TODO: implement me!
}

events::EventHandlerNonNull TextTrackListImp::getOnremovetrack()
{
    // TODO: implement me!
    return static_cast<Object*>(0);
}

void TextTrackListImp::setOnremovetrack(events::EventHandlerNonNull onremovetrack)
{
    // TODO: implement me!
}

}
}
}
}
