// Generated by esidl 0.2.1.
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "TextMetricsImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

double TextMetricsImp::getWidth()
{
    // TODO: implement me!
    return 0;
}

}
}
}
}
