// Generated by esidl (r1745).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "TimeRangesImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

unsigned int TimeRangesImp::getLength()
{
    // TODO: implement me!
    return 0;
}

float TimeRangesImp::start(unsigned int index)
{
    // TODO: implement me!
    return 0;
}

float TimeRangesImp::end(unsigned int index)
{
    // TODO: implement me!
    return 0;
}

}
}
}
}
