// Generated by esidl (r1745).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "ValidityStateImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

bool ValidityStateImp::getValueMissing()
{
    // TODO: implement me!
    return 0;
}

bool ValidityStateImp::getTypeMismatch()
{
    // TODO: implement me!
    return 0;
}

bool ValidityStateImp::getPatternMismatch()
{
    // TODO: implement me!
    return 0;
}

bool ValidityStateImp::getTooLong()
{
    // TODO: implement me!
    return 0;
}

bool ValidityStateImp::getRangeUnderflow()
{
    // TODO: implement me!
    return 0;
}

bool ValidityStateImp::getRangeOverflow()
{
    // TODO: implement me!
    return 0;
}

bool ValidityStateImp::getStepMismatch()
{
    // TODO: implement me!
    return 0;
}

bool ValidityStateImp::getCustomError()
{
    // TODO: implement me!
    return 0;
}

bool ValidityStateImp::getValid()
{
    // TODO: implement me!
    return 0;
}

}
}
}
}
