// Generated by esidl 0.3.0.
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#ifndef ORG_W3C_DOM_BOOTSTRAP_VIDEOTRACKLISTIMP_H_INCLUDED
#define ORG_W3C_DOM_BOOTSTRAP_VIDEOTRACKLISTIMP_H_INCLUDED

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <org/w3c/dom/html/VideoTrackList.h>
#include "EventTargetImp.h"

#include <org/w3c/dom/events/EventTarget.h>
#include <org/w3c/dom/events/EventHandlerNonNull.h>
#include <org/w3c/dom/html/VideoTrack.h>

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{
class VideoTrackListImp : public ObjectMixin<VideoTrackListImp, EventTargetImp>
{
public:
    // VideoTrackList
    unsigned int getLength();
    html::VideoTrack getElement(unsigned int index);
    html::VideoTrack getTrackById(const std::u16string& id);
    int getSelectedIndex();
    events::EventHandlerNonNull getOnchange();
    void setOnchange(events::EventHandlerNonNull onchange);
    events::EventHandlerNonNull getOnaddtrack();
    void setOnaddtrack(events::EventHandlerNonNull onaddtrack);
    events::EventHandlerNonNull getOnremovetrack();
    void setOnremovetrack(events::EventHandlerNonNull onremovetrack);
    // Object
    virtual Any message_(uint32_t selector, const char* id, int argc, Any* argv)
    {
        return html::VideoTrackList::dispatch(this, selector, id, argc, argv);
    }
    static const char* const getMetaData()
    {
        return html::VideoTrackList::getMetaData();
    }
};

}
}
}
}

#endif  // ORG_W3C_DOM_BOOTSTRAP_VIDEOTRACKLISTIMP_H_INCLUDED
