// Generated by esidl 0.3.0.
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "VideoTrackImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

std::u16string VideoTrackImp::getId()
{
    // TODO: implement me!
    return u"";
}

std::u16string VideoTrackImp::getKind()
{
    // TODO: implement me!
    return u"";
}

std::u16string VideoTrackImp::getLabel()
{
    // TODO: implement me!
    return u"";
}

std::u16string VideoTrackImp::getLanguage()
{
    // TODO: implement me!
    return u"";
}

bool VideoTrackImp::getSelected()
{
    // TODO: implement me!
    return 0;
}

void VideoTrackImp::setSelected(bool selected)
{
    // TODO: implement me!
}

}
}
}
}
