// Generated by esidl (r1745).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#ifndef ORG_W3C_DOM_BOOTSTRAP_BLOBIMP_H_INCLUDED
#define ORG_W3C_DOM_BOOTSTRAP_BLOBIMP_H_INCLUDED

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <org/w3c/dom/file/Blob.h>

#include <org/w3c/dom/file/Blob.h>

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{
class BlobImp : public ObjectMixin<BlobImp>
{
public:
    // Blob
    unsigned long long getSize() __attribute__((weak));
    std::u16string getType() __attribute__((weak));
    file::Blob slice(unsigned long long start, unsigned long long length) __attribute__((weak));
    file::Blob slice(unsigned long long start, unsigned long long length, std::u16string contentType) __attribute__((weak));
    // Object
    virtual Any message_(uint32_t selector, const char* id, int argc, Any* argv)
    {
        return file::Blob::dispatch(this, selector, id, argc, argv);
    }
    static const char* const getMetaData()
    {
        return file::Blob::getMetaData();
    }
};

}
}
}
}

#endif  // ORG_W3C_DOM_BOOTSTRAP_BLOBIMP_H_INCLUDED
