// Generated by esidl (r1745).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "BlobImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

unsigned long long BlobImp::getSize()
{
    // TODO: implement me!
    return 0;
}

std::u16string BlobImp::getType()
{
    // TODO: implement me!
    return u"";
}

file::Blob BlobImp::slice(unsigned long long start, unsigned long long length)
{
    // TODO: implement me!
    return static_cast<Object*>(0);
}

file::Blob BlobImp::slice(unsigned long long start, unsigned long long length, std::u16string contentType)
{
    // TODO: implement me!
    return static_cast<Object*>(0);
}

}
}
}
}
