// Generated by esidl (r1752).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "CustomEventInitImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

Any CustomEventInitImp::getDetail()
{
    // TODO: implement me!
    return 0;
}

void CustomEventInitImp::setDetail(Any detail)
{
    // TODO: implement me!
}

}
}
}
}
