// Generated by esidl (r1745).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "DocumentTraversalImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

traversal::NodeIterator DocumentTraversalImp::createNodeIterator(Node root, unsigned int whatToShow, traversal::NodeFilter filter, bool entityReferenceExpansion) throw(DOMException)
{
    // TODO: implement me!
    return static_cast<Object*>(0);
}

traversal::TreeWalker DocumentTraversalImp::createTreeWalker(Node root, unsigned int whatToShow, traversal::NodeFilter filter, bool entityReferenceExpansion) throw(DOMException)
{
    // TODO: implement me!
    return static_cast<Object*>(0);
}

}
}
}
}
