// Generated by esidl (r1745).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#ifndef ORG_W3C_DOM_BOOTSTRAP_DOCUMENTFRAGMENTIMP_H_INCLUDED
#define ORG_W3C_DOM_BOOTSTRAP_DOCUMENTFRAGMENTIMP_H_INCLUDED

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <org/w3c/dom/DocumentFragment.h>
#include "NodeImp.h"

#include <org/w3c/dom/Node.h>
#include <org/w3c/dom/Element.h>
#include <org/w3c/dom/NodeList.h>

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{
class DocumentFragmentImp : public ObjectMixin<DocumentFragmentImp, NodeImp>
{
public:
    // DocumentFragment
    // NodeSelector
    Element querySelector(std::u16string selectors);
    NodeList querySelectorAll(std::u16string selectors);
    // Object
    virtual Any message_(uint32_t selector, const char* id, int argc, Any* argv)
    {
        return DocumentFragment::dispatch(this, selector, id, argc, argv);
    }
    static const char* const getMetaData()
    {
        return DocumentFragment::getMetaData();
    }
};

}
}
}
}

#endif  // ORG_W3C_DOM_BOOTSTRAP_DOCUMENTFRAGMENTIMP_H_INCLUDED
