// Generated by esidl (r1745).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#ifndef ORG_W3C_DOM_BOOTSTRAP_DOMSTRINGLISTIMP_H_INCLUDED
#define ORG_W3C_DOM_BOOTSTRAP_DOMSTRINGLISTIMP_H_INCLUDED

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <org/w3c/dom/DOMStringList.h>

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{
class DOMStringListImp : public ObjectMixin<DOMStringListImp>
{
public:
    // DOMStringList
    unsigned int getLength() __attribute__((weak));
    std::u16string item(unsigned int index) __attribute__((weak));
    bool contains(std::u16string string) __attribute__((weak));
    // Object
    virtual Any message_(uint32_t selector, const char* id, int argc, Any* argv)
    {
        return DOMStringList::dispatch(this, selector, id, argc, argv);
    }
    static const char* const getMetaData()
    {
        return DOMStringList::getMetaData();
    }
};

}
}
}
}

#endif  // ORG_W3C_DOM_BOOTSTRAP_DOMSTRINGLISTIMP_H_INCLUDED
