// Generated by esidl (r1745).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "DOMStringListImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

unsigned int DOMStringListImp::getLength()
{
    // TODO: implement me!
    return 0;
}

std::u16string DOMStringListImp::item(unsigned int index)
{
    // TODO: implement me!
    return u"";
}

bool DOMStringListImp::contains(std::u16string string)
{
    // TODO: implement me!
    return 0;
}

}
}
}
}
