// Generated by esidl (r1745).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "DOMStringMapImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

std::u16string DOMStringMapImp::getElement(std::u16string name)
{
    // TODO: implement me!
    return u"";
}

void DOMStringMapImp::setElement(std::u16string name, std::u16string value)
{
    // TODO: implement me!
}

void DOMStringMapImp::createElement(std::u16string name, std::u16string value)
{
    // TODO: implement me!
}

void DOMStringMapImp::deleteElement(std::u16string name)
{
    // TODO: implement me!
}

}
}
}
}
