// Generated by esidl (r1745).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "DOMTokenListImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

unsigned int DOMTokenListImp::getLength()
{
    // TODO: implement me!
    return 0;
}

std::u16string DOMTokenListImp::item(unsigned int index)
{
    // TODO: implement me!
    return u"";
}

bool DOMTokenListImp::contains(std::u16string token)
{
    // TODO: implement me!
    return 0;
}

void DOMTokenListImp::add(std::u16string token)
{
    // TODO: implement me!
}

void DOMTokenListImp::remove(std::u16string token)
{
    // TODO: implement me!
}

bool DOMTokenListImp::toggle(std::u16string token)
{
    // TODO: implement me!
    return 0;
}

std::u16string DOMTokenListImp::toString()
{
    // TODO: implement me!
    return u"";
}

}
}
}
}
