// Generated by esidl (r1745).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#ifndef ORG_W3C_DOM_BOOTSTRAP_DRAGEVENTIMP_H_INCLUDED
#define ORG_W3C_DOM_BOOTSTRAP_DRAGEVENTIMP_H_INCLUDED

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <org/w3c/dom/html/DragEvent.h>
#include "MouseEventImp.h"

#include <org/w3c/dom/events/MouseEvent.h>
#include <org/w3c/dom/events/EventTarget.h>
#include <org/w3c/dom/html/DataTransfer.h>

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{
class DragEventImp : public ObjectMixin<DragEventImp, MouseEventImp>
{
public:
    // DragEvent
    html::DataTransfer getDataTransfer() __attribute__((weak));
    void initDragEvent(std::u16string typeArg, bool canBubbleArg, bool cancelableArg, Any dummyArg, int detailArg, int screenXArg, int screenYArg, int clientXArg, int clientYArg, bool ctrlKeyArg, bool altKeyArg, bool shiftKeyArg, bool metaKeyArg, unsigned short buttonArg, events::EventTarget relatedTargetArg, html::DataTransfer dataTransferArg) __attribute__((weak));
    // Object
    virtual Any message_(uint32_t selector, const char* id, int argc, Any* argv)
    {
        return html::DragEvent::dispatch(this, selector, id, argc, argv);
    }
    static const char* const getMetaData()
    {
        return html::DragEvent::getMetaData();
    }
};

}
}
}
}

#endif  // ORG_W3C_DOM_BOOTSTRAP_DRAGEVENTIMP_H_INCLUDED
