// Generated by esidl (r1745).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#ifndef ORG_W3C_DOM_BOOTSTRAP_MEDIAERRORIMP_H_INCLUDED
#define ORG_W3C_DOM_BOOTSTRAP_MEDIAERRORIMP_H_INCLUDED

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <org/w3c/dom/html/MediaError.h>

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{
class MediaErrorImp : public ObjectMixin<MediaErrorImp>
{
public:
    // MediaError
    unsigned short getCode() __attribute__((weak));
    // Object
    virtual Any message_(uint32_t selector, const char* id, int argc, Any* argv)
    {
        return html::MediaError::dispatch(this, selector, id, argc, argv);
    }
    static const char* const getMetaData()
    {
        return html::MediaError::getMetaData();
    }
};

}
}
}
}

#endif  // ORG_W3C_DOM_BOOTSTRAP_MEDIAERRORIMP_H_INCLUDED
