// Generated by esidl (r1745).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#ifndef ORG_W3C_DOM_BOOTSTRAP_MESSAGECHANNELIMP_H_INCLUDED
#define ORG_W3C_DOM_BOOTSTRAP_MESSAGECHANNELIMP_H_INCLUDED

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <org/w3c/dom/html/MessageChannel.h>

#include <org/w3c/dom/html/MessageChannel.h>
#include <org/w3c/dom/html/MessagePort.h>

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{
class MessageChannelImp : public ObjectMixin<MessageChannelImp>
{
public:
    // MessageChannel
    html::MessagePort getPort1() __attribute__((weak));
    html::MessagePort getPort2() __attribute__((weak));
    // Object
    virtual Any message_(uint32_t selector, const char* id, int argc, Any* argv)
    {
        return html::MessageChannel::dispatch(this, selector, id, argc, argv);
    }
    static const char* const getMetaData()
    {
        return html::MessageChannel::getMetaData();
    }
};

}
}
}
}

#endif  // ORG_W3C_DOM_BOOTSTRAP_MESSAGECHANNELIMP_H_INCLUDED
