// Generated by esidl (r1745).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#ifndef ORG_W3C_DOM_BOOTSTRAP_MUTATIONNAMEEVENTIMP_H_INCLUDED
#define ORG_W3C_DOM_BOOTSTRAP_MUTATIONNAMEEVENTIMP_H_INCLUDED

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <org/w3c/dom/events/MutationNameEvent.h>
#include "MutationEventImp.h"

#include <org/w3c/dom/events/MutationEvent.h>
#include <org/w3c/dom/Node.h>

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{
class MutationNameEventImp : public ObjectMixin<MutationNameEventImp, MutationEventImp>
{
public:
    // MutationNameEvent
    std::u16string getPrevNamespaceURI() __attribute__((weak));
    std::u16string getPrevNodeName() __attribute__((weak));
    void initMutationNameEvent(std::u16string typeArg, bool canBubbleArg, bool cancelableArg, Node relatedNodeArg, std::u16string prevNamespaceURIArg, std::u16string prevNodeNameArg) __attribute__((weak));
    // Object
    virtual Any message_(uint32_t selector, const char* id, int argc, Any* argv)
    {
        return events::MutationNameEvent::dispatch(this, selector, id, argc, argv);
    }
    static const char* const getMetaData()
    {
        return events::MutationNameEvent::getMetaData();
    }
};

}
}
}
}

#endif  // ORG_W3C_DOM_BOOTSTRAP_MUTATIONNAMEEVENTIMP_H_INCLUDED
