// Generated by esidl (r1745).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "NameListImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

Nullable<std::u16string> NameListImp::getName(unsigned int index)
{
    // TODO: implement me!
    return u"";
}

Nullable<std::u16string> NameListImp::getNamespaceURI(unsigned int index)
{
    // TODO: implement me!
    return u"";
}

unsigned int NameListImp::getLength()
{
    // TODO: implement me!
    return 0;
}

bool NameListImp::contains(Nullable<std::u16string> str)
{
    // TODO: implement me!
    return 0;
}

bool NameListImp::containsNS(Nullable<std::u16string> namespaceURI, Nullable<std::u16string> name)
{
    // TODO: implement me!
    return 0;
}

}
}
}
}
