// Generated by esidl (r1752).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "NavigatorImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

std::u16string NavigatorImp::getAppName()
{
    // TODO: implement me!
    return u"";
}

std::u16string NavigatorImp::getAppVersion()
{
    // TODO: implement me!
    return u"";
}

std::u16string NavigatorImp::getPlatform()
{
    // TODO: implement me!
    return u"";
}

std::u16string NavigatorImp::getUserAgent()
{
    // TODO: implement me!
    return u"";
}

bool NavigatorImp::getOnLine()
{
    // TODO: implement me!
    return 0;
}

void NavigatorImp::registerProtocolHandler(std::u16string scheme, std::u16string url, std::u16string title)
{
    // TODO: implement me!
}

void NavigatorImp::registerContentHandler(std::u16string mimeType, std::u16string url, std::u16string title)
{
    // TODO: implement me!
}

void NavigatorImp::yieldForStorageUpdates()
{
    // TODO: implement me!
}

void NavigatorImp::getUserMedia(std::u16string options, html::NavigatorUserMediaSuccessCallback successCallback)
{
    // TODO: implement me!
}

void NavigatorImp::getUserMedia(std::u16string options, html::NavigatorUserMediaSuccessCallback successCallback, html::NavigatorUserMediaErrorCallback errorCallback)
{
    // TODO: implement me!
}

}
}
}
}
