// Generated by esidl (r1745).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#ifndef ORG_W3C_DOM_BOOTSTRAP_PROPERTYNODELISTIMP_H_INCLUDED
#define ORG_W3C_DOM_BOOTSTRAP_PROPERTYNODELISTIMP_H_INCLUDED

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <org/w3c/dom/html/PropertyNodeList.h>
#include "NodeListImp.h"

#include <org/w3c/dom/NodeList.h>

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{
class PropertyNodeListImp : public ObjectMixin<PropertyNodeListImp, NodeListImp>
{
public:
    // PropertyNodeList
    html::PropertyValueArray getValues() __attribute__((weak));
    // Object
    virtual Any message_(uint32_t selector, const char* id, int argc, Any* argv)
    {
        return html::PropertyNodeList::dispatch(this, selector, id, argc, argv);
    }
    static const char* const getMetaData()
    {
        return html::PropertyNodeList::getMetaData();
    }
};

}
}
}
}

#endif  // ORG_W3C_DOM_BOOTSTRAP_PROPERTYNODELISTIMP_H_INCLUDED
