// Generated by esidl (r1745).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "TextEventImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

std::u16string TextEventImp::getData()
{
    // TODO: implement me!
    return u"";
}

unsigned int TextEventImp::getInputMethod()
{
    // TODO: implement me!
    return 0;
}

std::u16string TextEventImp::getLocale()
{
    // TODO: implement me!
    return u"";
}

void TextEventImp::initTextEvent(std::u16string typeArg, bool canBubbleArg, bool cancelableArg, html::Window viewArg, std::u16string dataArg, unsigned int inputMethod, std::u16string localeArg)
{
    // TODO: implement me!
}

}
}
}
}
