// Generated by esidl (r1745).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "UndoManagerImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

unsigned int UndoManagerImp::getLength()
{
    // TODO: implement me!
    return 0;
}

Any UndoManagerImp::item(unsigned int index)
{
    // TODO: implement me!
    return 0;
}

unsigned int UndoManagerImp::getPosition()
{
    // TODO: implement me!
    return 0;
}

unsigned int UndoManagerImp::add(Any data, std::u16string title)
{
    // TODO: implement me!
    return 0;
}

void UndoManagerImp::remove(unsigned int index)
{
    // TODO: implement me!
}

void UndoManagerImp::clearUndo()
{
    // TODO: implement me!
}

void UndoManagerImp::clearRedo()
{
    // TODO: implement me!
}

}
}
}
}
