// Generated by esidl (r1745).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#ifndef ORG_W3C_DOM_BOOTSTRAP_UNDOMANAGEREVENTIMP_H_INCLUDED
#define ORG_W3C_DOM_BOOTSTRAP_UNDOMANAGEREVENTIMP_H_INCLUDED

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <org/w3c/dom/html/UndoManagerEvent.h>
#include "EventImp.h"

#include <org/w3c/dom/events/Event.h>

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{
class UndoManagerEventImp : public ObjectMixin<UndoManagerEventImp, EventImp>
{
public:
    // UndoManagerEvent
    Any getData() __attribute__((weak));
    void initUndoManagerEvent(std::u16string typeArg, bool canBubbleArg, bool cancelableArg, Any dataArg) __attribute__((weak));
    // Object
    virtual Any message_(uint32_t selector, const char* id, int argc, Any* argv)
    {
        return html::UndoManagerEvent::dispatch(this, selector, id, argc, argv);
    }
    static const char* const getMetaData()
    {
        return html::UndoManagerEvent::getMetaData();
    }
};

}
}
}
}

#endif  // ORG_W3C_DOM_BOOTSTRAP_UNDOMANAGEREVENTIMP_H_INCLUDED
