// Generated by esidl (r1745).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "Float64ArrayImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

unsigned int Float64ArrayImp::getLength()
{
    // TODO: implement me!
    return 0;
}

double Float64ArrayImp::get(unsigned int index)
{
    // TODO: implement me!
    return 0;
}

void Float64ArrayImp::set(unsigned int index, double value)
{
    // TODO: implement me!
}

void Float64ArrayImp::set(typedarray::Float64Array array)
{
    // TODO: implement me!
}

void Float64ArrayImp::set(typedarray::Float64Array array, unsigned int offset)
{
    // TODO: implement me!
}

void Float64ArrayImp::set(ObjectArray<double> array)
{
    // TODO: implement me!
}

void Float64ArrayImp::set(ObjectArray<double> array, unsigned int offset)
{
    // TODO: implement me!
}

typedarray::Float64Array Float64ArrayImp::subarray(int start, int end)
{
    // TODO: implement me!
    return static_cast<Object*>(0);
}

}
}
}
}
