// Generated by esidl (r1745).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "Int8ArrayImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

unsigned int Int8ArrayImp::getLength()
{
    // TODO: implement me!
    return 0;
}

signed char Int8ArrayImp::get(unsigned int index)
{
    // TODO: implement me!
    return 0;
}

void Int8ArrayImp::set(unsigned int index, signed char value)
{
    // TODO: implement me!
}

void Int8ArrayImp::set(typedarray::Int8Array array)
{
    // TODO: implement me!
}

void Int8ArrayImp::set(typedarray::Int8Array array, unsigned int offset)
{
    // TODO: implement me!
}

void Int8ArrayImp::set(ObjectArray<signed char> array)
{
    // TODO: implement me!
}

void Int8ArrayImp::set(ObjectArray<signed char> array, unsigned int offset)
{
    // TODO: implement me!
}

typedarray::Int8Array Int8ArrayImp::subarray(int start, int end)
{
    // TODO: implement me!
    return static_cast<Object*>(0);
}

}
}
}
}
