// Generated by esidl (r1745).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#ifndef ORG_W3C_DOM_BOOTSTRAP_ARRAYBUFFERIMP_H_INCLUDED
#define ORG_W3C_DOM_BOOTSTRAP_ARRAYBUFFERIMP_H_INCLUDED

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <org/w3c/dom/typedarray/ArrayBuffer.h>

#include <org/w3c/dom/typedarray/ArrayBuffer.h>

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{
class ArrayBufferImp : public ObjectMixin<ArrayBufferImp>
{
public:
    // ArrayBuffer
    unsigned int getByteLength();
    // Object
    virtual Any message_(uint32_t selector, const char* id, int argc, Any* argv)
    {
        return typedarray::ArrayBuffer::dispatch(this, selector, id, argc, argv);
    }
    static const char* const getMetaData()
    {
        return typedarray::ArrayBuffer::getMetaData();
    }
};

}
}
}
}

#endif  // ORG_W3C_DOM_BOOTSTRAP_ARRAYBUFFERIMP_H_INCLUDED
