// Generated by esidl 0.3.0.
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "Int16ArrayImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

unsigned int Int16ArrayImp::getLength()
{
    // TODO: implement me!
    return 0;
}

short Int16ArrayImp::get(unsigned int index)
{
    // TODO: implement me!
    return 0;
}

void Int16ArrayImp::set(unsigned int index, short value)
{
    // TODO: implement me!
}

void Int16ArrayImp::set(Int16Array array)
{
    // TODO: implement me!
}

void Int16ArrayImp::set(Int16Array array, unsigned int offset)
{
    // TODO: implement me!
}

void Int16ArrayImp::set(ObjectArray<short> array)
{
    // TODO: implement me!
}

void Int16ArrayImp::set(ObjectArray<short> array, unsigned int offset)
{
    // TODO: implement me!
}

Int16Array Int16ArrayImp::subarray(int start, int end)
{
    // TODO: implement me!
    return static_cast<Object*>(0);
}

ArrayBuffer Int16ArrayImp::getBuffer()
{
    // TODO: implement me!
    return static_cast<Object*>(0);
}

unsigned int Int16ArrayImp::getByteOffset()
{
    // TODO: implement me!
    return 0;
}

unsigned int Int16ArrayImp::getByteLength()
{
    // TODO: implement me!
    return 0;
}

}
}
}
}
