// Generated by esidl 0.3.0.
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "Int32ArrayImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

unsigned int Int32ArrayImp::getLength()
{
    // TODO: implement me!
    return 0;
}

int Int32ArrayImp::get(unsigned int index)
{
    // TODO: implement me!
    return 0;
}

void Int32ArrayImp::set(unsigned int index, int value)
{
    // TODO: implement me!
}

void Int32ArrayImp::set(Int32Array array)
{
    // TODO: implement me!
}

void Int32ArrayImp::set(Int32Array array, unsigned int offset)
{
    // TODO: implement me!
}

void Int32ArrayImp::set(ObjectArray<int> array)
{
    // TODO: implement me!
}

void Int32ArrayImp::set(ObjectArray<int> array, unsigned int offset)
{
    // TODO: implement me!
}

Int32Array Int32ArrayImp::subarray(int start, int end)
{
    // TODO: implement me!
    return nullptr;
}

ArrayBuffer Int32ArrayImp::getBuffer()
{
    // TODO: implement me!
    return nullptr;
}

unsigned int Int32ArrayImp::getByteOffset()
{
    // TODO: implement me!
    return 0;
}

unsigned int Int32ArrayImp::getByteLength()
{
    // TODO: implement me!
    return 0;
}

}
}
}
}
