// Generated by esidl (r1745).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "Uint16ArrayImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

unsigned int Uint16ArrayImp::getLength()
{
    // TODO: implement me!
    return 0;
}

unsigned short Uint16ArrayImp::get(unsigned int index)
{
    // TODO: implement me!
    return 0;
}

void Uint16ArrayImp::set(unsigned int index, unsigned short value)
{
    // TODO: implement me!
}

void Uint16ArrayImp::set(typedarray::Uint16Array array)
{
    // TODO: implement me!
}

void Uint16ArrayImp::set(typedarray::Uint16Array array, unsigned int offset)
{
    // TODO: implement me!
}

void Uint16ArrayImp::set(ObjectArray<unsigned short> array)
{
    // TODO: implement me!
}

void Uint16ArrayImp::set(ObjectArray<unsigned short> array, unsigned int offset)
{
    // TODO: implement me!
}

typedarray::Uint16Array Uint16ArrayImp::subarray(int start, int end)
{
    // TODO: implement me!
    return static_cast<Object*>(0);
}

}
}
}
}
