#!/bin/bash
#
# Copyright 2012, 2013 Esrille Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

BASE_BIN_DIR=`dirname $0`
BASE_DIR=`dirname $BASE_BIN_DIR`
if [ -d "$BASE_DIR/libexec/esrille" ];
then
BASE_LIBEXEC_DIR="$BASE_DIR/libexec/esrille/escudo"
else
BASE_LIBEXEC_DIR="$BASE_DIR/lib/esrille/escudo"
fi
BASE_DATA_DIR="$BASE_DIR/share/esrille/escudo"
PROFILE_DIR="$HOME/.esrille/escudo"

exec "$BASE_LIBEXEC_DIR/escudo" $BASE_DATA_DIR $PROFILE_DIR "$@"
