// Generated by esidl 0.2.1.
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "FormDataImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

void FormDataImp::append(const std::u16string& name, file::Blob value)
{
    // TODO: implement me!
}

void FormDataImp::append(const std::u16string& name, const std::u16string& value)
{
    // TODO: implement me!
}

}
}
}
}
