// Generated by esidl 0.3.0.
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "XMLHttpRequestEventTargetImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

events::EventHandlerNonNull XMLHttpRequestEventTargetImp::getOnloadstart()
{
    // TODO: implement me!
    return static_cast<Object*>(0);
}

void XMLHttpRequestEventTargetImp::setOnloadstart(events::EventHandlerNonNull onloadstart)
{
    // TODO: implement me!
}

events::EventHandlerNonNull XMLHttpRequestEventTargetImp::getOnprogress()
{
    // TODO: implement me!
    return static_cast<Object*>(0);
}

void XMLHttpRequestEventTargetImp::setOnprogress(events::EventHandlerNonNull onprogress)
{
    // TODO: implement me!
}

events::EventHandlerNonNull XMLHttpRequestEventTargetImp::getOnabort()
{
    // TODO: implement me!
    return static_cast<Object*>(0);
}

void XMLHttpRequestEventTargetImp::setOnabort(events::EventHandlerNonNull onabort)
{
    // TODO: implement me!
}

events::EventHandlerNonNull XMLHttpRequestEventTargetImp::getOnerror()
{
    // TODO: implement me!
    return static_cast<Object*>(0);
}

void XMLHttpRequestEventTargetImp::setOnerror(events::EventHandlerNonNull onerror)
{
    // TODO: implement me!
}

events::EventHandlerNonNull XMLHttpRequestEventTargetImp::getOnload()
{
    // TODO: implement me!
    return static_cast<Object*>(0);
}

void XMLHttpRequestEventTargetImp::setOnload(events::EventHandlerNonNull onload)
{
    // TODO: implement me!
}

events::EventHandlerNonNull XMLHttpRequestEventTargetImp::getOntimeout()
{
    // TODO: implement me!
    return static_cast<Object*>(0);
}

void XMLHttpRequestEventTargetImp::setOntimeout(events::EventHandlerNonNull ontimeout)
{
    // TODO: implement me!
}

events::EventHandlerNonNull XMLHttpRequestEventTargetImp::getOnloadend()
{
    // TODO: implement me!
    return static_cast<Object*>(0);
}

void XMLHttpRequestEventTargetImp::setOnloadend(events::EventHandlerNonNull onloadend)
{
    // TODO: implement me!
}

}
}
}
}
