// Generated by esidl (r1752).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "DataTransferItemImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

std::u16string DataTransferItemImp::getKind()
{
    // TODO: implement me!
    return u"";
}

std::u16string DataTransferItemImp::getType()
{
    // TODO: implement me!
    return u"";
}

void DataTransferItemImp::getAsString(html::FunctionStringCallback callback)
{
    // TODO: implement me!
}

file::File DataTransferItemImp::getAsFile()
{
    // TODO: implement me!
    return static_cast<Object*>(0);
}

}
}
}
}
