// Generated by esidl (r1752).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#ifndef ORG_W3C_DOM_BOOTSTRAP_DATATRANSFERIMP_H_INCLUDED
#define ORG_W3C_DOM_BOOTSTRAP_DATATRANSFERIMP_H_INCLUDED

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <org/w3c/dom/html/DataTransfer.h>

#include <org/w3c/dom/Element.h>
#include <org/w3c/dom/DOMStringList.h>
#include <org/w3c/dom/file/FileList.h>
#include <org/w3c/dom/html/DataTransferItemList.h>

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{
class DataTransferImp : public ObjectMixin<DataTransferImp>
{
public:
    // DataTransfer
    std::u16string getDropEffect() __attribute__((weak));
    void setDropEffect(std::u16string dropEffect) __attribute__((weak));
    std::u16string getEffectAllowed() __attribute__((weak));
    void setEffectAllowed(std::u16string effectAllowed) __attribute__((weak));
    html::DataTransferItemList getItems() __attribute__((weak));
    void setDragImage(Element image, int x, int y) __attribute__((weak));
    void addElement(Element element) __attribute__((weak));
    DOMStringList getTypes() __attribute__((weak));
    std::u16string getData(std::u16string format) __attribute__((weak));
    void setData(std::u16string format, std::u16string data) __attribute__((weak));
    void clearData() __attribute__((weak));
    void clearData(std::u16string format) __attribute__((weak));
    file::FileList getFiles() __attribute__((weak));
    // Object
    virtual Any message_(uint32_t selector, const char* id, int argc, Any* argv)
    {
        return html::DataTransfer::dispatch(this, selector, id, argc, argv);
    }
    static const char* const getMetaData()
    {
        return html::DataTransfer::getMetaData();
    }
};

}
}
}
}

#endif  // ORG_W3C_DOM_BOOTSTRAP_DATATRANSFERIMP_H_INCLUDED
