// Generated by esidl (r1745).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "HTMLTimeElementImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

std::u16string HTMLTimeElementImp::getDateTime()
{
    // TODO: implement me!
    return u"";
}

void HTMLTimeElementImp::setDateTime(std::u16string dateTime)
{
    // TODO: implement me!
}

bool HTMLTimeElementImp::getPubDate()
{
    // TODO: implement me!
    return 0;
}

void HTMLTimeElementImp::setPubDate(bool pubDate)
{
    // TODO: implement me!
}

unsigned long long HTMLTimeElementImp::getValueAsDate()
{
    // TODO: implement me!
    return 0;
}

}
}
}
}
