// Generated by esidl (r1745).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "HTMLMapElementImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

std::u16string HTMLMapElementImp::getName()
{
    // TODO: implement me!
    return u"";
}

void HTMLMapElementImp::setName(std::u16string name)
{
    // TODO: implement me!
}

html::HTMLCollection HTMLMapElementImp::getAreas()
{
    // TODO: implement me!
    return static_cast<Object*>(0);
}

html::HTMLCollection HTMLMapElementImp::getImages()
{
    // TODO: implement me!
    return static_cast<Object*>(0);
}

}
}
}
}
