// Generated by esidl (r1745).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#ifndef ORG_W3C_DOM_BOOTSTRAP_HTMLTABLEDATACELLELEMENTIMP_H_INCLUDED
#define ORG_W3C_DOM_BOOTSTRAP_HTMLTABLEDATACELLELEMENTIMP_H_INCLUDED

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <org/w3c/dom/html/HTMLTableDataCellElement.h>
#include "HTMLTableCellElementImp.h"

#include <org/w3c/dom/html/HTMLTableCellElement.h>

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{
class HTMLTableDataCellElementImp : public ObjectMixin<HTMLTableDataCellElementImp, HTMLTableCellElementImp>
{
public:
    // HTMLTableDataCellElement
    // Object
    virtual Any message_(uint32_t selector, const char* id, int argc, Any* argv)
    {
        return html::HTMLTableDataCellElement::dispatch(this, selector, id, argc, argv);
    }
    static const char* const getMetaData()
    {
        return html::HTMLTableDataCellElement::getMetaData();
    }
    HTMLTableDataCellElementImp(DocumentImp* ownerDocument) :
        ObjectMixin(ownerDocument, u"td") {
    }
    HTMLTableDataCellElementImp(HTMLTableDataCellElementImp* org, bool deep) :
        ObjectMixin(org, deep) {
    }
};

}
}
}
}

#endif  // ORG_W3C_DOM_BOOTSTRAP_HTMLTABLEDATACELLELEMENTIMP_H_INCLUDED
