// Generated by esidl (r1745).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "HTMLOptionsCollectionImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

unsigned int HTMLOptionsCollectionImp::getLength()
{
    // TODO: implement me!
    return 0;
}

void HTMLOptionsCollectionImp::setLength(unsigned int length)
{
    // TODO: implement me!
}

Object HTMLOptionsCollectionImp::namedItem(std::u16string name)
{
    // TODO: implement me!
    return static_cast<Object*>(0);
}

void HTMLOptionsCollectionImp::add(html::HTMLElement element)
{
    // TODO: implement me!
}

void HTMLOptionsCollectionImp::add(html::HTMLElement element, html::HTMLElement before)
{
    // TODO: implement me!
}

void HTMLOptionsCollectionImp::add(html::HTMLElement element, int before)
{
    // TODO: implement me!
}

void HTMLOptionsCollectionImp::remove(int index)
{
    // TODO: implement me!
}

}
}
}
}
