// Generated by esidl (r1745).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "HTMLLIElementImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

int HTMLLIElementImp::getValue()
{
    // TODO: implement me!
    return 0;
}

void HTMLLIElementImp::setValue(int value)
{
    // TODO: implement me!
}

std::u16string HTMLLIElementImp::getType()
{
    // TODO: implement me!
    return u"";
}

void HTMLLIElementImp::setType(std::u16string type)
{
    // TODO: implement me!
}

}
}
}
}
