// Generated by esidl (r1745).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#ifndef ORG_W3C_DOM_BOOTSTRAP_HTMLMENUELEMENTIMP_H_INCLUDED
#define ORG_W3C_DOM_BOOTSTRAP_HTMLMENUELEMENTIMP_H_INCLUDED

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <org/w3c/dom/html/HTMLMenuElement.h>
#include "HTMLElementImp.h"

#include <org/w3c/dom/html/HTMLElement.h>

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{
class HTMLMenuElementImp : public ObjectMixin<HTMLMenuElementImp, HTMLElementImp>
{
public:
    // HTMLMenuElement
    std::u16string getType();
    void setType(std::u16string type);
    Nullable<std::u16string> getLabel();
    void setLabel(Nullable<std::u16string> label);
    // HTMLMenuElement-22
    bool getCompact();
    void setCompact(bool compact);
    // Object
    virtual Any message_(uint32_t selector, const char* id, int argc, Any* argv)
    {
        return html::HTMLMenuElement::dispatch(this, selector, id, argc, argv);
    }
    static const char* const getMetaData()
    {
        return html::HTMLMenuElement::getMetaData();
    }
    HTMLMenuElementImp(DocumentImp* ownerDocument) :
        ObjectMixin(ownerDocument, u"menu") {
    }
    HTMLMenuElementImp(HTMLMenuElementImp* org, bool deep) :
        ObjectMixin(org, deep) {
    }
};

}
}
}
}

#endif  // ORG_W3C_DOM_BOOTSTRAP_HTMLMENUELEMENTIMP_H_INCLUDED
