// Generated by esidl (r1745).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "HTMLTableCellElementImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

unsigned int HTMLTableCellElementImp::getColSpan()
{
    // TODO: implement me!
    return 0;
}

void HTMLTableCellElementImp::setColSpan(unsigned int colSpan)
{
    // TODO: implement me!
}

unsigned int HTMLTableCellElementImp::getRowSpan()
{
    // TODO: implement me!
    return 0;
}

void HTMLTableCellElementImp::setRowSpan(unsigned int rowSpan)
{
    // TODO: implement me!
}

DOMSettableTokenList HTMLTableCellElementImp::getHeaders()
{
    // TODO: implement me!
    return static_cast<Object*>(0);
}

void HTMLTableCellElementImp::setHeaders(std::u16string headers)
{
    // TODO: implement me!
}

int HTMLTableCellElementImp::getCellIndex()
{
    // TODO: implement me!
    return 0;
}

std::u16string HTMLTableCellElementImp::getAbbr()
{
    // TODO: implement me!
    return u"";
}

void HTMLTableCellElementImp::setAbbr(std::u16string abbr)
{
    // TODO: implement me!
}

std::u16string HTMLTableCellElementImp::getAlign()
{
    // TODO: implement me!
    return u"";
}

void HTMLTableCellElementImp::setAlign(std::u16string align)
{
    // TODO: implement me!
}

std::u16string HTMLTableCellElementImp::getAxis()
{
    // TODO: implement me!
    return u"";
}

void HTMLTableCellElementImp::setAxis(std::u16string axis)
{
    // TODO: implement me!
}

std::u16string HTMLTableCellElementImp::getBgColor()
{
    // TODO: implement me!
    return u"";
}

void HTMLTableCellElementImp::setBgColor(std::u16string bgColor)
{
    // TODO: implement me!
}

std::u16string HTMLTableCellElementImp::getCh()
{
    // TODO: implement me!
    return u"";
}

void HTMLTableCellElementImp::setCh(std::u16string ch)
{
    // TODO: implement me!
}

std::u16string HTMLTableCellElementImp::getChOff()
{
    // TODO: implement me!
    return u"";
}

void HTMLTableCellElementImp::setChOff(std::u16string chOff)
{
    // TODO: implement me!
}

std::u16string HTMLTableCellElementImp::getHeight()
{
    // TODO: implement me!
    return u"";
}

void HTMLTableCellElementImp::setHeight(std::u16string height)
{
    // TODO: implement me!
}

bool HTMLTableCellElementImp::getNoWrap()
{
    // TODO: implement me!
    return 0;
}

void HTMLTableCellElementImp::setNoWrap(bool noWrap)
{
    // TODO: implement me!
}

std::u16string HTMLTableCellElementImp::getVAlign()
{
    // TODO: implement me!
    return u"";
}

void HTMLTableCellElementImp::setVAlign(std::u16string vAlign)
{
    // TODO: implement me!
}

std::u16string HTMLTableCellElementImp::getWidth()
{
    // TODO: implement me!
    return u"";
}

void HTMLTableCellElementImp::setWidth(std::u16string width)
{
    // TODO: implement me!
}

}
}
}
}
