// Generated by esidl (r1745).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "HTMLButtonElementImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

bool HTMLButtonElementImp::getAutofocus()
{
    // TODO: implement me!
    return 0;
}

void HTMLButtonElementImp::setAutofocus(bool autofocus)
{
    // TODO: implement me!
}

bool HTMLButtonElementImp::getDisabled()
{
    // TODO: implement me!
    return 0;
}

void HTMLButtonElementImp::setDisabled(bool disabled)
{
    // TODO: implement me!
}

html::HTMLFormElement HTMLButtonElementImp::getForm()
{
    // TODO: implement me!
    return static_cast<Object*>(0);
}

std::u16string HTMLButtonElementImp::getFormAction()
{
    // TODO: implement me!
    return u"";
}

void HTMLButtonElementImp::setFormAction(std::u16string formAction)
{
    // TODO: implement me!
}

std::u16string HTMLButtonElementImp::getFormEnctype()
{
    // TODO: implement me!
    return u"";
}

void HTMLButtonElementImp::setFormEnctype(std::u16string formEnctype)
{
    // TODO: implement me!
}

std::u16string HTMLButtonElementImp::getFormMethod()
{
    // TODO: implement me!
    return u"";
}

void HTMLButtonElementImp::setFormMethod(std::u16string formMethod)
{
    // TODO: implement me!
}

std::u16string HTMLButtonElementImp::getFormNoValidate()
{
    // TODO: implement me!
    return u"";
}

void HTMLButtonElementImp::setFormNoValidate(std::u16string formNoValidate)
{
    // TODO: implement me!
}

std::u16string HTMLButtonElementImp::getFormTarget()
{
    // TODO: implement me!
    return u"";
}

void HTMLButtonElementImp::setFormTarget(std::u16string formTarget)
{
    // TODO: implement me!
}

std::u16string HTMLButtonElementImp::getName()
{
    // TODO: implement me!
    return u"";
}

void HTMLButtonElementImp::setName(std::u16string name)
{
    // TODO: implement me!
}

std::u16string HTMLButtonElementImp::getType()
{
    // TODO: implement me!
    return u"";
}

void HTMLButtonElementImp::setType(std::u16string type)
{
    // TODO: implement me!
}

std::u16string HTMLButtonElementImp::getValue()
{
    // TODO: implement me!
    return u"";
}

void HTMLButtonElementImp::setValue(std::u16string value)
{
    // TODO: implement me!
}

bool HTMLButtonElementImp::getWillValidate()
{
    // TODO: implement me!
    return 0;
}

html::ValidityState HTMLButtonElementImp::getValidity()
{
    // TODO: implement me!
    return static_cast<Object*>(0);
}

std::u16string HTMLButtonElementImp::getValidationMessage()
{
    // TODO: implement me!
    return u"";
}

bool HTMLButtonElementImp::checkValidity()
{
    // TODO: implement me!
    return 0;
}

void HTMLButtonElementImp::setCustomValidity(std::u16string error)
{
    // TODO: implement me!
}

NodeList HTMLButtonElementImp::getLabels()
{
    // TODO: implement me!
    return static_cast<Object*>(0);
}

}
}
}
}
