// Generated by esidl (r1745).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "HTMLSourceElementImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

std::u16string HTMLSourceElementImp::getSrc()
{
    // TODO: implement me!
    return u"";
}

void HTMLSourceElementImp::setSrc(std::u16string src)
{
    // TODO: implement me!
}

std::u16string HTMLSourceElementImp::getType()
{
    // TODO: implement me!
    return u"";
}

void HTMLSourceElementImp::setType(std::u16string type)
{
    // TODO: implement me!
}

std::u16string HTMLSourceElementImp::getMedia()
{
    // TODO: implement me!
    return u"";
}

void HTMLSourceElementImp::setMedia(std::u16string media)
{
    // TODO: implement me!
}

}
}
}
}
