// Generated by esidl (r1745).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "HTMLTableRowElementImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

int HTMLTableRowElementImp::getRowIndex()
{
    // TODO: implement me!
    return 0;
}

int HTMLTableRowElementImp::getSectionRowIndex()
{
    // TODO: implement me!
    return 0;
}

html::HTMLCollection HTMLTableRowElementImp::getCells()
{
    // TODO: implement me!
    return static_cast<Object*>(0);
}

html::HTMLElement HTMLTableRowElementImp::insertCell()
{
    // TODO: implement me!
    return static_cast<Object*>(0);
}

html::HTMLElement HTMLTableRowElementImp::insertCell(int index)
{
    // TODO: implement me!
    return static_cast<Object*>(0);
}

void HTMLTableRowElementImp::deleteCell(int index)
{
    // TODO: implement me!
}

std::u16string HTMLTableRowElementImp::getAlign()
{
    // TODO: implement me!
    return u"";
}

void HTMLTableRowElementImp::setAlign(std::u16string align)
{
    // TODO: implement me!
}

std::u16string HTMLTableRowElementImp::getBgColor()
{
    // TODO: implement me!
    return u"";
}

void HTMLTableRowElementImp::setBgColor(std::u16string bgColor)
{
    // TODO: implement me!
}

std::u16string HTMLTableRowElementImp::getCh()
{
    // TODO: implement me!
    return u"";
}

void HTMLTableRowElementImp::setCh(std::u16string ch)
{
    // TODO: implement me!
}

std::u16string HTMLTableRowElementImp::getChOff()
{
    // TODO: implement me!
    return u"";
}

void HTMLTableRowElementImp::setChOff(std::u16string chOff)
{
    // TODO: implement me!
}

std::u16string HTMLTableRowElementImp::getVAlign()
{
    // TODO: implement me!
    return u"";
}

void HTMLTableRowElementImp::setVAlign(std::u16string vAlign)
{
    // TODO: implement me!
}

}
}
}
}
