// Generated by esidl (r1745).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#ifndef ORG_W3C_DOM_BOOTSTRAP_HTMLTABLEELEMENTIMP_H_INCLUDED
#define ORG_W3C_DOM_BOOTSTRAP_HTMLTABLEELEMENTIMP_H_INCLUDED

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <org/w3c/dom/html/HTMLTableElement.h>
#include "HTMLElementImp.h"

#include <org/w3c/dom/html/HTMLElement.h>
#include <org/w3c/dom/html/HTMLCollection.h>
#include <org/w3c/dom/html/HTMLTableCaptionElement.h>
#include <org/w3c/dom/html/HTMLTableSectionElement.h>

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{
class HTMLTableElementImp : public ObjectMixin<HTMLTableElementImp, HTMLElementImp>
{
public:
    // HTMLTableElement
    html::HTMLTableCaptionElement getCaption();
    void setCaption(html::HTMLTableCaptionElement caption);
    html::HTMLElement createCaption();
    void deleteCaption();
    html::HTMLTableSectionElement getTHead();
    void setTHead(html::HTMLTableSectionElement tHead);
    html::HTMLElement createTHead();
    void deleteTHead();
    html::HTMLTableSectionElement getTFoot();
    void setTFoot(html::HTMLTableSectionElement tFoot);
    html::HTMLElement createTFoot();
    void deleteTFoot();
    html::HTMLCollection getTBodies();
    html::HTMLElement createTBody();
    html::HTMLCollection getRows();
    html::HTMLElement insertRow();
    html::HTMLElement insertRow(int index);
    void deleteRow(int index);
    std::u16string getSummary();
    void setSummary(std::u16string summary);
    // HTMLTableElement-30
    std::u16string getAlign();
    void setAlign(std::u16string align);
    std::u16string getBgColor();
    void setBgColor(std::u16string bgColor);
    std::u16string getBorder();
    void setBorder(std::u16string border);
    std::u16string getCellPadding();
    void setCellPadding(std::u16string cellPadding);
    std::u16string getCellSpacing();
    void setCellSpacing(std::u16string cellSpacing);
    std::u16string getFrame();
    void setFrame(std::u16string frame);
    std::u16string getRules();
    void setRules(std::u16string rules);
    std::u16string getWidth();
    void setWidth(std::u16string width);
    // Object
    virtual Any message_(uint32_t selector, const char* id, int argc, Any* argv)
    {
        return html::HTMLTableElement::dispatch(this, selector, id, argc, argv);
    }
    static const char* const getMetaData()
    {
        return html::HTMLTableElement::getMetaData();
    }
    HTMLTableElementImp(DocumentImp* ownerDocument) :
        ObjectMixin(ownerDocument, u"table") {
    }
    HTMLTableElementImp(HTMLTableElementImp* org, bool deep) :
        ObjectMixin(org, deep) {
    }
};

}
}
}
}

#endif  // ORG_W3C_DOM_BOOTSTRAP_HTMLTABLEELEMENTIMP_H_INCLUDED
