// Generated by esidl (r1752).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#ifndef ORG_W3C_DOM_BOOTSTRAP_HTMLOPTIONSCOLLECTIONIMP_H_INCLUDED
#define ORG_W3C_DOM_BOOTSTRAP_HTMLOPTIONSCOLLECTIONIMP_H_INCLUDED

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <org/w3c/dom/html/HTMLOptionsCollection.h>
#include "HTMLCollectionImp.h"

#include <org/w3c/dom/html/HTMLElement.h>
#include <org/w3c/dom/html/HTMLCollection.h>

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{
class HTMLOptionsCollectionImp : public ObjectMixin<HTMLOptionsCollectionImp, HTMLCollectionImp>
{
public:
    // HTMLOptionsCollection
    unsigned int getLength() __attribute__((weak));
    void setLength(unsigned int length) __attribute__((weak));
    Object namedItem(std::u16string name) __attribute__((weak));
    void add(html::HTMLElement element) __attribute__((weak));
    void add(html::HTMLElement element, html::HTMLElement before) __attribute__((weak));
    void add(html::HTMLElement element, int before) __attribute__((weak));
    void remove(int index) __attribute__((weak));
    int getSelectedIndex() __attribute__((weak));
    void setSelectedIndex(int selectedIndex) __attribute__((weak));
    // Object
    virtual Any message_(uint32_t selector, const char* id, int argc, Any* argv)
    {
        return html::HTMLOptionsCollection::dispatch(this, selector, id, argc, argv);
    }
    static const char* const getMetaData()
    {
        return html::HTMLOptionsCollection::getMetaData();
    }
};

}
}
}
}

#endif  // ORG_W3C_DOM_BOOTSTRAP_HTMLOPTIONSCOLLECTIONIMP_H_INCLUDED
