// Generated by esidl (r1745).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "HTMLMeterElementImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

float HTMLMeterElementImp::getValue()
{
    // TODO: implement me!
    return 0;
}

void HTMLMeterElementImp::setValue(float value)
{
    // TODO: implement me!
}

float HTMLMeterElementImp::getMin()
{
    // TODO: implement me!
    return 0;
}

void HTMLMeterElementImp::setMin(float min)
{
    // TODO: implement me!
}

float HTMLMeterElementImp::getMax()
{
    // TODO: implement me!
    return 0;
}

void HTMLMeterElementImp::setMax(float max)
{
    // TODO: implement me!
}

float HTMLMeterElementImp::getLow()
{
    // TODO: implement me!
    return 0;
}

void HTMLMeterElementImp::setLow(float low)
{
    // TODO: implement me!
}

float HTMLMeterElementImp::getHigh()
{
    // TODO: implement me!
    return 0;
}

void HTMLMeterElementImp::setHigh(float high)
{
    // TODO: implement me!
}

float HTMLMeterElementImp::getOptimum()
{
    // TODO: implement me!
    return 0;
}

void HTMLMeterElementImp::setOptimum(float optimum)
{
    // TODO: implement me!
}

html::HTMLFormElement HTMLMeterElementImp::getForm()
{
    // TODO: implement me!
    return static_cast<Object*>(0);
}

NodeList HTMLMeterElementImp::getLabels()
{
    // TODO: implement me!
    return static_cast<Object*>(0);
}

}
}
}
}
