// Generated by esidl (r1745).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#ifndef ORG_W3C_DOM_BOOTSTRAP_HTMLOLISTELEMENTIMP_H_INCLUDED
#define ORG_W3C_DOM_BOOTSTRAP_HTMLOLISTELEMENTIMP_H_INCLUDED

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <org/w3c/dom/html/HTMLOListElement.h>
#include "HTMLElementImp.h"

#include <org/w3c/dom/html/HTMLElement.h>

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{
class HTMLOListElementImp : public ObjectMixin<HTMLOListElementImp, HTMLElementImp>
{
public:
    // HTMLOListElement
    bool getReversed() __attribute__((weak));
    void setReversed(bool reversed) __attribute__((weak));
    int getStart() __attribute__((weak));
    void setStart(int start) __attribute__((weak));
    // HTMLOListElement-25
    bool getCompact() __attribute__((weak));
    void setCompact(bool compact) __attribute__((weak));
    std::u16string getType() __attribute__((weak));
    void setType(std::u16string type) __attribute__((weak));
    // Object
    virtual Any message_(uint32_t selector, const char* id, int argc, Any* argv)
    {
        return html::HTMLOListElement::dispatch(this, selector, id, argc, argv);
    }
    static const char* const getMetaData()
    {
        return html::HTMLOListElement::getMetaData();
    }
    HTMLOListElementImp(DocumentImp* ownerDocument) :
        ObjectMixin(ownerDocument, u"ol") {
    }
    HTMLOListElementImp(HTMLOListElementImp* org, bool deep) :
        ObjectMixin(org, deep) {
    }
};

}
}
}
}

#endif  // ORG_W3C_DOM_BOOTSTRAP_HTMLOLISTELEMENTIMP_H_INCLUDED
