// Generated by esidl (r1745).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "HTMLProgressElementImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

float HTMLProgressElementImp::getValue()
{
    // TODO: implement me!
    return 0;
}

void HTMLProgressElementImp::setValue(float value)
{
    // TODO: implement me!
}

float HTMLProgressElementImp::getMax()
{
    // TODO: implement me!
    return 0;
}

void HTMLProgressElementImp::setMax(float max)
{
    // TODO: implement me!
}

float HTMLProgressElementImp::getPosition()
{
    // TODO: implement me!
    return 0;
}

html::HTMLFormElement HTMLProgressElementImp::getForm()
{
    // TODO: implement me!
    return static_cast<Object*>(0);
}

NodeList HTMLProgressElementImp::getLabels()
{
    // TODO: implement me!
    return static_cast<Object*>(0);
}

}
}
}
}
