// Generated by esidl (r1745).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "HTMLQuoteElementImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

std::u16string HTMLQuoteElementImp::getCite()
{
    // TODO: implement me!
    return u"";
}

void HTMLQuoteElementImp::setCite(std::u16string cite)
{
    // TODO: implement me!
}

}
}
}
}
