// Generated by esidl (r1745).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#ifndef ORG_W3C_DOM_BOOTSTRAP_HTMLFONTELEMENTIMP_H_INCLUDED
#define ORG_W3C_DOM_BOOTSTRAP_HTMLFONTELEMENTIMP_H_INCLUDED

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <org/w3c/dom/html/HTMLFontElement.h>
#include "HTMLElementImp.h"

#include <org/w3c/dom/html/HTMLElement.h>

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{
class HTMLFontElementImp : public ObjectMixin<HTMLFontElementImp, HTMLElementImp>
{
public:
    // HTMLFontElement
    std::u16string getColor() __attribute__((weak));
    void setColor(std::u16string color) __attribute__((weak));
    std::u16string getFace() __attribute__((weak));
    void setFace(std::u16string face) __attribute__((weak));
    std::u16string getSize() __attribute__((weak));
    void setSize(std::u16string size) __attribute__((weak));
    // Object
    virtual Any message_(uint32_t selector, const char* id, int argc, Any* argv)
    {
        return html::HTMLFontElement::dispatch(this, selector, id, argc, argv);
    }
    static const char* const getMetaData()
    {
        return html::HTMLFontElement::getMetaData();
    }
    HTMLFontElementImp(DocumentImp* ownerDocument) :
        ObjectMixin(ownerDocument, u"font") {
    }
    HTMLFontElementImp(HTMLFontElementImp* org, bool deep) :
        ObjectMixin(org, deep) {
    }
};

}
}
}
}

#endif  // ORG_W3C_DOM_BOOTSTRAP_HTMLFONTELEMENTIMP_H_INCLUDED
