// Generated by esidl (r1745).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "HTMLMenuElementImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

std::u16string HTMLMenuElementImp::getType()
{
    // TODO: implement me!
    return u"";
}

void HTMLMenuElementImp::setType(std::u16string type)
{
    // TODO: implement me!
}

std::u16string HTMLMenuElementImp::getLabel()
{
    // TODO: implement me!
    return u"";
}

void HTMLMenuElementImp::setLabel(std::u16string label)
{
    // TODO: implement me!
}

bool HTMLMenuElementImp::getCompact()
{
    // TODO: implement me!
    return 0;
}

void HTMLMenuElementImp::setCompact(bool compact)
{
    // TODO: implement me!
}

}
}
}
}
