// Generated by esidl (r1745).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "HTMLTableColElementImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

unsigned int HTMLTableColElementImp::getSpan()
{
    // TODO: implement me!
    return 0;
}

void HTMLTableColElementImp::setSpan(unsigned int span)
{
    // TODO: implement me!
}

std::u16string HTMLTableColElementImp::getAlign()
{
    // TODO: implement me!
    return u"";
}

void HTMLTableColElementImp::setAlign(std::u16string align)
{
    // TODO: implement me!
}

std::u16string HTMLTableColElementImp::getCh()
{
    // TODO: implement me!
    return u"";
}

void HTMLTableColElementImp::setCh(std::u16string ch)
{
    // TODO: implement me!
}

std::u16string HTMLTableColElementImp::getChOff()
{
    // TODO: implement me!
    return u"";
}

void HTMLTableColElementImp::setChOff(std::u16string chOff)
{
    // TODO: implement me!
}

std::u16string HTMLTableColElementImp::getVAlign()
{
    // TODO: implement me!
    return u"";
}

void HTMLTableColElementImp::setVAlign(std::u16string vAlign)
{
    // TODO: implement me!
}

std::u16string HTMLTableColElementImp::getWidth()
{
    // TODO: implement me!
    return u"";
}

void HTMLTableColElementImp::setWidth(std::u16string width)
{
    // TODO: implement me!
}

}
}
}
}
