// Generated by esidl (r1752).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#ifndef ORG_W3C_DOM_BOOTSTRAP_HTMLCANVASELEMENTIMP_H_INCLUDED
#define ORG_W3C_DOM_BOOTSTRAP_HTMLCANVASELEMENTIMP_H_INCLUDED

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <org/w3c/dom/html/HTMLCanvasElement.h>
#include "HTMLElementImp.h"

#include <org/w3c/dom/html/HTMLElement.h>
#include <org/w3c/dom/file/FileCallback.h>

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{
class HTMLCanvasElementImp : public ObjectMixin<HTMLCanvasElementImp, HTMLElementImp>
{
public:
    HTMLCanvasElementImp(DocumentImp* ownerDocument) :
        ObjectMixin(ownerDocument, u"canvas") {
    }
    HTMLCanvasElementImp(HTMLCanvasElementImp* org, bool deep) :
        ObjectMixin(org, deep) {
    }

    // HTMLCanvasElement
    unsigned int getWidth();
    void setWidth(unsigned int width);
    unsigned int getHeight();
    void setHeight(unsigned int height);
    std::u16string toDataURL();
    std::u16string toDataURL(std::u16string type, Variadic<Any> args = Variadic<Any>());
    void toBlob(file::FileCallback callback);
    void toBlob(file::FileCallback callback, std::u16string type, Variadic<Any> args = Variadic<Any>());
    Object getContext(std::u16string contextId, Variadic<Any> args = Variadic<Any>());
    // Object
    virtual Any message_(uint32_t selector, const char* id, int argc, Any* argv)
    {
        return html::HTMLCanvasElement::dispatch(this, selector, id, argc, argv);
    }
    static const char* const getMetaData()
    {
        return html::HTMLCanvasElement::getMetaData();
    }
};

}
}
}
}

#endif  // ORG_W3C_DOM_BOOTSTRAP_HTMLCANVASELEMENTIMP_H_INCLUDED
