// Generated by esidl (r1745).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#ifndef ORG_W3C_DOM_BOOTSTRAP_HTMLTABLECOLELEMENTIMP_H_INCLUDED
#define ORG_W3C_DOM_BOOTSTRAP_HTMLTABLECOLELEMENTIMP_H_INCLUDED

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <org/w3c/dom/html/HTMLTableColElement.h>
#include "HTMLElementImp.h"

#include <org/w3c/dom/html/HTMLElement.h>

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{
class HTMLTableColElementImp : public ObjectMixin<HTMLTableColElementImp, HTMLElementImp>
{
public:
    // HTMLTableColElement
    unsigned int getSpan() __attribute__((weak));
    void setSpan(unsigned int span) __attribute__((weak));
    // HTMLTableColElement-9
    std::u16string getAlign() __attribute__((weak));
    void setAlign(std::u16string align) __attribute__((weak));
    std::u16string getCh() __attribute__((weak));
    void setCh(std::u16string ch) __attribute__((weak));
    std::u16string getChOff() __attribute__((weak));
    void setChOff(std::u16string chOff) __attribute__((weak));
    std::u16string getVAlign() __attribute__((weak));
    void setVAlign(std::u16string vAlign) __attribute__((weak));
    std::u16string getWidth() __attribute__((weak));
    void setWidth(std::u16string width) __attribute__((weak));
    // Object
    virtual Any message_(uint32_t selector, const char* id, int argc, Any* argv)
    {
        return html::HTMLTableColElement::dispatch(this, selector, id, argc, argv);
    }
    static const char* const getMetaData()
    {
        return html::HTMLTableColElement::getMetaData();
    }
    HTMLTableColElementImp(DocumentImp* ownerDocument, const std::u16string& localName = u"col") :
        ObjectMixin(ownerDocument, localName) {
    }
    HTMLTableColElementImp(HTMLTableColElementImp* org, bool deep) :
        ObjectMixin(org, deep) {
    }
};

}
}
}
}

#endif  // ORG_W3C_DOM_BOOTSTRAP_HTMLTABLECOLELEMENTIMP_H_INCLUDED
