// Generated by esidl (r1745).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "HTMLOptGroupElementImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

bool HTMLOptGroupElementImp::getDisabled()
{
    // TODO: implement me!
    return 0;
}

void HTMLOptGroupElementImp::setDisabled(bool disabled)
{
    // TODO: implement me!
}

std::u16string HTMLOptGroupElementImp::getLabel()
{
    // TODO: implement me!
    return u"";
}

void HTMLOptGroupElementImp::setLabel(std::u16string label)
{
    // TODO: implement me!
}

}
}
}
}
