// Generated by esidl (r1745).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#ifndef ORG_W3C_DOM_BOOTSTRAP_HTMLHRELEMENTIMP_H_INCLUDED
#define ORG_W3C_DOM_BOOTSTRAP_HTMLHRELEMENTIMP_H_INCLUDED

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <org/w3c/dom/html/HTMLHRElement.h>
#include "HTMLElementImp.h"

#include <org/w3c/dom/html/HTMLElement.h>

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{
class HTMLHRElementImp : public ObjectMixin<HTMLHRElementImp, HTMLElementImp>
{
public:
    // HTMLHRElement
    // HTMLHRElement-14
    std::u16string getAlign();
    void setAlign(std::u16string align);
    std::u16string getColor();
    void setColor(std::u16string color);
    bool getNoShade();
    void setNoShade(bool noShade);
    std::u16string getSize();
    void setSize(std::u16string size);
    std::u16string getWidth();
    void setWidth(std::u16string width);
    // Object
    virtual Any message_(uint32_t selector, const char* id, int argc, Any* argv)
    {
        return html::HTMLHRElement::dispatch(this, selector, id, argc, argv);
    }
    static const char* const getMetaData()
    {
        return html::HTMLHRElement::getMetaData();
    }
    HTMLHRElementImp(DocumentImp* ownerDocument) :
        ObjectMixin(ownerDocument, u"hr") {
    }
    HTMLHRElementImp(HTMLHRElementImp* org, bool deep) :
        ObjectMixin(org, deep) {
    }
};

}
}
}
}

#endif  // ORG_W3C_DOM_BOOTSTRAP_HTMLHRELEMENTIMP_H_INCLUDED
