// Generated by esidl (r1745).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#ifndef ORG_W3C_DOM_BOOTSTRAP_TIMERANGESIMP_H_INCLUDED
#define ORG_W3C_DOM_BOOTSTRAP_TIMERANGESIMP_H_INCLUDED

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <org/w3c/dom/html/TimeRanges.h>

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{
class TimeRangesImp : public ObjectMixin<TimeRangesImp>
{
public:
    // TimeRanges
    unsigned int getLength() __attribute__((weak));
    float start(unsigned int index) __attribute__((weak));
    float end(unsigned int index) __attribute__((weak));
    // Object
    virtual Any message_(uint32_t selector, const char* id, int argc, Any* argv)
    {
        return html::TimeRanges::dispatch(this, selector, id, argc, argv);
    }
    static const char* const getMetaData()
    {
        return html::TimeRanges::getMetaData();
    }
};

}
}
}
}

#endif  // ORG_W3C_DOM_BOOTSTRAP_TIMERANGESIMP_H_INCLUDED
