// Generated by esidl (r1745).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "CSSLengthComponentValueImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

float CSSLengthComponentValueImp::getEm()
{
    // TODO: implement me!
    return 0;
}

void CSSLengthComponentValueImp::setEm(float em)
{
    // TODO: implement me!
}

float CSSLengthComponentValueImp::getEx()
{
    // TODO: implement me!
    return 0;
}

void CSSLengthComponentValueImp::setEx(float ex)
{
    // TODO: implement me!
}

float CSSLengthComponentValueImp::getPx()
{
    // TODO: implement me!
    return 0;
}

void CSSLengthComponentValueImp::setPx(float px)
{
    // TODO: implement me!
}

}
}
}
}
