// Generated by esidl 0.2.1.
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "DOMImplementationCSSImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

css::CSSStyleSheet DOMImplementationCSSImp::createCSSStyleSheet(const std::u16string& title, const std::u16string& media) throw(DOMException)
{
    // TODO: implement me!
    return static_cast<Object*>(0);
}

}
}
}
}
