/*
 * selectors.idl
 *
 * Selectors API Level 1
 *
 * Original W3C Proposed Recommendation 13 December 2012:
 *
 *   http://www.w3.org/TR/2012/PR-selectors-api-20121213/
 */

module dom {

partial interface Document {
  Element?  querySelector(DOMString selectors);
  NodeList  querySelectorAll(DOMString selectors);
};

partial interface DocumentFragment {
  Element?  querySelector(DOMString selectors);
  NodeList  querySelectorAll(DOMString selectors);
};

partial interface Element {
  Element?  querySelector(DOMString selectors);
  NodeList  querySelectorAll(DOMString selectors);
};

};
