// Generated by esidl (r1745).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#ifndef ORG_W3C_DOM_BOOTSTRAP_FILEREADERIMP_H_INCLUDED
#define ORG_W3C_DOM_BOOTSTRAP_FILEREADERIMP_H_INCLUDED

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <org/w3c/dom/file/FileReader.h>
#include "EventTargetImp.h"

#include <org/w3c/dom/events/EventTarget.h>
#include <org/w3c/dom/file/Blob.h>
#include <org/w3c/dom/file/FileReader.h>
#include <org/w3c/dom/file/FileError.h>
#include <org/w3c/dom/html/Function.h>

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{
class FileReaderImp : public ObjectMixin<FileReaderImp, EventTargetImp>
{
public:
    // FileReader
    void readAsArrayBuffer(file::Blob blob);
    void readAsBinaryString(file::Blob blob);
    void readAsText(file::Blob blob);
    void readAsText(file::Blob blob, std::u16string encoding);
    void readAsDataURL(file::Blob blob);
    void abort();
    unsigned short getReadyState();
    Any getResult();
    file::FileError getError();
    html::Function getOnloadstart();
    void setOnloadstart(html::Function onloadstart);
    html::Function getOnprogress();
    void setOnprogress(html::Function onprogress);
    html::Function getOnload();
    void setOnload(html::Function onload);
    html::Function getOnabort();
    void setOnabort(html::Function onabort);
    html::Function getOnerror();
    void setOnerror(html::Function onerror);
    html::Function getOnloadend();
    void setOnloadend(html::Function onloadend);
    // Object
    virtual Any message_(uint32_t selector, const char* id, int argc, Any* argv)
    {
        return file::FileReader::dispatch(this, selector, id, argc, argv);
    }
    static const char* const getMetaData()
    {
        return file::FileReader::getMetaData();
    }
};

}
}
}
}

#endif  // ORG_W3C_DOM_BOOTSTRAP_FILEREADERIMP_H_INCLUDED
