// Generated by esidl 0.3.0.
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "FileReaderSyncImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

ArrayBuffer FileReaderSyncImp::readAsArrayBuffer(file::Blob blob)
{
    // TODO: implement me!
    return static_cast<Object*>(0);
}

std::u16string FileReaderSyncImp::readAsText(file::Blob blob)
{
    // TODO: implement me!
    return u"";
}

std::u16string FileReaderSyncImp::readAsText(file::Blob blob, const std::u16string& encoding)
{
    // TODO: implement me!
    return u"";
}

std::u16string FileReaderSyncImp::readAsDataURL(file::Blob blob)
{
    // TODO: implement me!
    return u"";
}

}
}
}
}
