// Generated by esidl (r1745).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "BarPropImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

bool BarPropImp::getVisible()
{
    // TODO: implement me!
    return 0;
}

void BarPropImp::setVisible(bool visible)
{
    // TODO: implement me!
}

}
}
}
}
