// Generated by esidl 0.3.0.
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "ClientRectListImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

unsigned int ClientRectListImp::getLength()
{
    // TODO: implement me!
    return 0;
}

views::ClientRect ClientRectListImp::item(unsigned int index)
{
    // TODO: implement me!
    return nullptr;
}

}
}
}
}
