// Generated by esidl 0.3.0.
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "CustomEventImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

Any CustomEventImp::getDetail()
{
    // TODO: implement me!
    return 0;
}

void CustomEventImp::initCustomEvent(const std::u16string& typeArg, bool canBubbleArg, bool cancelableArg, Any detailArg)
{
    // TODO: implement me!
}

}
}
}
}
