// Generated by esidl 0.3.0.
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#ifndef ORG_W3C_DOM_BOOTSTRAP_DOMELEMENTMAPIMP_H_INCLUDED
#define ORG_W3C_DOM_BOOTSTRAP_DOMELEMENTMAPIMP_H_INCLUDED

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <org/w3c/dom/DOMElementMap.h>

#include <org/w3c/dom/Element.h>

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{
class DOMElementMapImp : public ObjectMixin<DOMElementMapImp>
{
public:
    // DOMElementMap
    std::u16string getElement(const std::u16string& name);
    void setElement(const std::u16string& name, Element value);
    void createElement(const std::u16string& name, Element value);
    void deleteElement(const std::u16string& name);
    // Object
    virtual Any message_(uint32_t selector, const char* id, int argc, Any* argv)
    {
        return DOMElementMap::dispatch(this, selector, id, argc, argv);
    }
    static const char* const getMetaData()
    {
        return DOMElementMap::getMetaData();
    }
};

}
}
}
}

#endif  // ORG_W3C_DOM_BOOTSTRAP_DOMELEMENTMAPIMP_H_INCLUDED
