// Generated by esidl 0.3.0.
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#ifndef ORG_W3C_DOM_BOOTSTRAP_DOMPARSERIMP_H_INCLUDED
#define ORG_W3C_DOM_BOOTSTRAP_DOMPARSERIMP_H_INCLUDED

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <org/w3c/dom/DOMParser.h>

#include <org/w3c/dom/Document.h>
#include <org/w3c/dom/DOMParser.h>

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{
class DOMParserImp : public ObjectMixin<DOMParserImp>
{
public:
    // DOMParser
    Document parseFromString(const std::u16string& str, const SupportedType& type);
    // Object
    virtual Any message_(uint32_t selector, const char* id, int argc, Any* argv)
    {
        return DOMParser::dispatch(this, selector, id, argc, argv);
    }
    static const char* const getMetaData()
    {
        return DOMParser::getMetaData();
    }
};

}
}
}
}

#endif  // ORG_W3C_DOM_BOOTSTRAP_DOMPARSERIMP_H_INCLUDED
