// Generated by esidl 0.4.0.
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "DOMPointInitImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

double DOMPointInitImp::getX()
{
    // TODO: implement me!
    return 0;
}

void DOMPointInitImp::setX(double x)
{
    // TODO: implement me!
}

double DOMPointInitImp::getY()
{
    // TODO: implement me!
    return 0;
}

void DOMPointInitImp::setY(double y)
{
    // TODO: implement me!
}

double DOMPointInitImp::getZ()
{
    // TODO: implement me!
    return 0;
}

void DOMPointInitImp::setZ(double z)
{
    // TODO: implement me!
}

double DOMPointInitImp::getW()
{
    // TODO: implement me!
    return 0;
}

void DOMPointInitImp::setW(double w)
{
    // TODO: implement me!
}

}
}
}
}
