// Generated by esidl 0.4.0.
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "DOMQuadImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

DOMPoint DOMQuadImp::getP1()
{
    // TODO: implement me!
    return nullptr;
}

DOMPoint DOMQuadImp::getP2()
{
    // TODO: implement me!
    return nullptr;
}

DOMPoint DOMQuadImp::getP3()
{
    // TODO: implement me!
    return nullptr;
}

DOMPoint DOMQuadImp::getP4()
{
    // TODO: implement me!
    return nullptr;
}

DOMRectReadOnly DOMQuadImp::getBounds()
{
    // TODO: implement me!
    return nullptr;
}

}
}
}
}
