// Generated by esidl 0.4.0.
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "DOMRectListImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

unsigned int DOMRectListImp::getLength()
{
    // TODO: implement me!
    return 0;
}

DOMRect DOMRectListImp::item(unsigned int index)
{
    // TODO: implement me!
    return nullptr;
}

}
}
}
}
