// Generated by esidl 0.4.0.
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#ifndef ORG_W3C_DOM_BOOTSTRAP_DOMRECTLISTIMP_H_INCLUDED
#define ORG_W3C_DOM_BOOTSTRAP_DOMRECTLISTIMP_H_INCLUDED

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <org/w3c/dom/DOMRectList.h>

#include <org/w3c/dom/DOMRect.h>

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{
class DOMRectListImp : public ObjectMixin<DOMRectListImp>
{
public:
    // DOMRectList
    unsigned int getLength();
    DOMRect item(unsigned int index);
    // Object
    virtual Any message_(uint32_t selector, const char* id, int argc, Any* argv)
    {
        return DOMRectList::dispatch(this, selector, id, argc, argv);
    }
    static const char* const getMetaData()
    {
        return DOMRectList::getMetaData();
    }
};

}
}
}
}

#endif  // ORG_W3C_DOM_BOOTSTRAP_DOMRECTLISTIMP_H_INCLUDED
