// Generated by esidl 0.4.0.
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "DOMRectReadOnlyImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

double DOMRectReadOnlyImp::getX()
{
    // TODO: implement me!
    return 0;
}

double DOMRectReadOnlyImp::getY()
{
    // TODO: implement me!
    return 0;
}

double DOMRectReadOnlyImp::getWidth()
{
    // TODO: implement me!
    return 0;
}

double DOMRectReadOnlyImp::getHeight()
{
    // TODO: implement me!
    return 0;
}

double DOMRectReadOnlyImp::getTop()
{
    // TODO: implement me!
    return 0;
}

double DOMRectReadOnlyImp::getRight()
{
    // TODO: implement me!
    return 0;
}

double DOMRectReadOnlyImp::getBottom()
{
    // TODO: implement me!
    return 0;
}

double DOMRectReadOnlyImp::getLeft()
{
    // TODO: implement me!
    return 0;
}

}
}
}
}
