// Generated by esidl 0.2.1.
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "DOMSettableTokenListImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

std::u16string DOMSettableTokenListImp::getValue()
{
    // TODO: implement me!
    return u"";
}

void DOMSettableTokenListImp::setValue(const std::u16string& value)
{
    // TODO: implement me!
}

}
}
}
}
