// Generated by esidl 0.3.0.
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "DragEventInitImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

html::Window DragEventInitImp::getView()
{
    // TODO: implement me!
    return static_cast<Object*>(0);
}

void DragEventInitImp::setView(html::Window view)
{
    // TODO: implement me!
}

int DragEventInitImp::getDetail()
{
    // TODO: implement me!
    return 0;
}

void DragEventInitImp::setDetail(int detail)
{
    // TODO: implement me!
}

int DragEventInitImp::getScreenX()
{
    // TODO: implement me!
    return 0;
}

void DragEventInitImp::setScreenX(int screenX)
{
    // TODO: implement me!
}

int DragEventInitImp::getScreenY()
{
    // TODO: implement me!
    return 0;
}

void DragEventInitImp::setScreenY(int screenY)
{
    // TODO: implement me!
}

int DragEventInitImp::getClientX()
{
    // TODO: implement me!
    return 0;
}

void DragEventInitImp::setClientX(int clientX)
{
    // TODO: implement me!
}

int DragEventInitImp::getClientY()
{
    // TODO: implement me!
    return 0;
}

void DragEventInitImp::setClientY(int clientY)
{
    // TODO: implement me!
}

bool DragEventInitImp::getCtrlKey()
{
    // TODO: implement me!
    return 0;
}

void DragEventInitImp::setCtrlKey(bool ctrlKey)
{
    // TODO: implement me!
}

bool DragEventInitImp::getShiftKey()
{
    // TODO: implement me!
    return 0;
}

void DragEventInitImp::setShiftKey(bool shiftKey)
{
    // TODO: implement me!
}

bool DragEventInitImp::getAltKey()
{
    // TODO: implement me!
    return 0;
}

void DragEventInitImp::setAltKey(bool altKey)
{
    // TODO: implement me!
}

bool DragEventInitImp::getMetaKey()
{
    // TODO: implement me!
    return 0;
}

void DragEventInitImp::setMetaKey(bool metaKey)
{
    // TODO: implement me!
}

unsigned short DragEventInitImp::getButton()
{
    // TODO: implement me!
    return 0;
}

void DragEventInitImp::setButton(unsigned short button)
{
    // TODO: implement me!
}

unsigned short DragEventInitImp::getButtons()
{
    // TODO: implement me!
    return 0;
}

void DragEventInitImp::setButtons(unsigned short buttons)
{
    // TODO: implement me!
}

events::EventTarget DragEventInitImp::getRelatedTarget()
{
    // TODO: implement me!
    return static_cast<Object*>(0);
}

void DragEventInitImp::setRelatedTarget(events::EventTarget relatedTarget)
{
    // TODO: implement me!
}

html::DataTransfer DragEventInitImp::getDataTransfer()
{
    // TODO: implement me!
    return static_cast<Object*>(0);
}

void DragEventInitImp::setDataTransfer(html::DataTransfer dataTransfer)
{
    // TODO: implement me!
}

}
}
}
}
