// Generated by esidl 0.3.0.
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "DragEventImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

html::DataTransfer DragEventImp::getDataTransfer()
{
    // TODO: implement me!
    return nullptr;
}

}
}
}
}
