// Generated by esidl (r1752).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "EventInitImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

bool EventInitImp::getBubbles()
{
    // TODO: implement me!
    return 0;
}

void EventInitImp::setBubbles(bool bubbles)
{
    // TODO: implement me!
}

bool EventInitImp::getCancelable()
{
    // TODO: implement me!
    return 0;
}

void EventInitImp::setCancelable(bool cancelable)
{
    // TODO: implement me!
}

}
}
}
}
