// Generated by esidl 0.3.0.
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "EventSourceImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

std::u16string EventSourceImp::getUrl()
{
    // TODO: implement me!
    return u"";
}

unsigned short EventSourceImp::getReadyState()
{
    // TODO: implement me!
    return 0;
}

events::EventHandlerNonNull EventSourceImp::getOnopen()
{
    // TODO: implement me!
    return static_cast<Object*>(0);
}

void EventSourceImp::setOnopen(events::EventHandlerNonNull onopen)
{
    // TODO: implement me!
}

events::EventHandlerNonNull EventSourceImp::getOnmessage()
{
    // TODO: implement me!
    return static_cast<Object*>(0);
}

void EventSourceImp::setOnmessage(events::EventHandlerNonNull onmessage)
{
    // TODO: implement me!
}

events::EventHandlerNonNull EventSourceImp::getOnerror()
{
    // TODO: implement me!
    return static_cast<Object*>(0);
}

void EventSourceImp::setOnerror(events::EventHandlerNonNull onerror)
{
    // TODO: implement me!
}

void EventSourceImp::close()
{
    // TODO: implement me!
}

}
}
}
}
