// Generated by esidl 0.3.0.
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#ifndef ORG_W3C_DOM_BOOTSTRAP_FOCUSEVENTINITIMP_H_INCLUDED
#define ORG_W3C_DOM_BOOTSTRAP_FOCUSEVENTINITIMP_H_INCLUDED

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <org/w3c/dom/events/FocusEventInit.h>

#include <org/w3c/dom/events/EventTarget.h>
#include <org/w3c/dom/html/Window.h>

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{
class FocusEventInitImp : public ObjectMixin<FocusEventInitImp>
{
public:
    // FocusEventInit
    bool getBubbles();
    void setBubbles(bool bubbles);
    bool getCancelable();
    void setCancelable(bool cancelable);
    html::Window getView();
    void setView(html::Window view);
    int getDetail();
    void setDetail(int detail);
    events::EventTarget getRelatedTarget();
    void setRelatedTarget(events::EventTarget relatedTarget);
    // Object
    virtual Any message_(uint32_t selector, const char* id, int argc, Any* argv)
    {
        return events::FocusEventInit::dispatch(this, selector, id, argc, argv);
    }
    static const char* const getMetaData()
    {
        return events::FocusEventInit::getMetaData();
    }
};

}
}
}
}

#endif  // ORG_W3C_DOM_BOOTSTRAP_FOCUSEVENTINITIMP_H_INCLUDED
