// Generated by esidl (r1745).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "FocusEventImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

events::EventTarget FocusEventImp::getRelatedTarget()
{
    // TODO: implement me!
    return static_cast<Object*>(0);
}

void FocusEventImp::initFocusEvent(std::u16string typeArg, bool canBubbleArg, bool cancelableArg, html::Window viewArg, int detailArg, events::EventTarget relatedTargetArg)
{
    // TODO: implement me!
}

}
}
}
}
