// Generated by esidl 0.3.0.
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "HashChangeEventInitImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

std::u16string HashChangeEventInitImp::getOldURL()
{
    // TODO: implement me!
    return u"";
}

void HashChangeEventInitImp::setOldURL(const std::u16string& oldURL)
{
    // TODO: implement me!
}

std::u16string HashChangeEventInitImp::getNewURL()
{
    // TODO: implement me!
    return u"";
}

void HashChangeEventInitImp::setNewURL(const std::u16string& newURL)
{
    // TODO: implement me!
}

}
}
}
}
