// Generated by esidl 0.2.1.
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "HashChangeEventImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

std::u16string HashChangeEventImp::getOldURL()
{
    // TODO: implement me!
    return u"";
}

std::u16string HashChangeEventImp::getNewURL()
{
    // TODO: implement me!
    return u"";
}

void HashChangeEventImp::initHashChangeEvent(const std::u16string& typeArg, bool canBubbleArg, bool cancelableArg, const std::u16string& oldURLArg, const std::u16string& newURLArg)
{
    // TODO: implement me!
}

}
}
}
}
