// Generated by esidl 0.3.0.
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#ifndef ORG_W3C_DOM_BOOTSTRAP_HASHCHANGEEVENTINITIMP_H_INCLUDED
#define ORG_W3C_DOM_BOOTSTRAP_HASHCHANGEEVENTINITIMP_H_INCLUDED

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <org/w3c/dom/html/HashChangeEventInit.h>
#include "EventInitImp.h"

#include <org/w3c/dom/events/EventInit.h>

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{
class HashChangeEventInitImp : public ObjectMixin<HashChangeEventInitImp, EventInitImp>
{
public:
    // HashChangeEventInit
    std::u16string getOldURL();
    void setOldURL(const std::u16string& oldURL);
    std::u16string getNewURL();
    void setNewURL(const std::u16string& newURL);
    // Object
    virtual Any message_(uint32_t selector, const char* id, int argc, Any* argv)
    {
        return html::HashChangeEventInit::dispatch(this, selector, id, argc, argv);
    }
    static const char* const getMetaData()
    {
        return html::HashChangeEventInit::getMetaData();
    }
};

}
}
}
}

#endif  // ORG_W3C_DOM_BOOTSTRAP_HASHCHANGEEVENTINITIMP_H_INCLUDED
