// Generated by esidl 0.3.0.
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#ifndef ORG_W3C_DOM_BOOTSTRAP_KEYBOARDEVENTINITIMP_H_INCLUDED
#define ORG_W3C_DOM_BOOTSTRAP_KEYBOARDEVENTINITIMP_H_INCLUDED

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <org/w3c/dom/events/KeyboardEventInit.h>

#include <org/w3c/dom/html/Window.h>

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{
class KeyboardEventInitImp : public ObjectMixin<KeyboardEventInitImp>
{
public:
    // KeyboardEventInit
    bool getBubbles();
    void setBubbles(bool bubbles);
    bool getCancelable();
    void setCancelable(bool cancelable);
    html::Window getView();
    void setView(html::Window view);
    int getDetail();
    void setDetail(int detail);
    std::u16string getChar();
    void setChar(const std::u16string& _char);
    std::u16string getKey();
    void setKey(const std::u16string& key);
    unsigned int getLocation();
    void setLocation(unsigned int location);
    bool getCtrlKey();
    void setCtrlKey(bool ctrlKey);
    bool getShiftKey();
    void setShiftKey(bool shiftKey);
    bool getAltKey();
    void setAltKey(bool altKey);
    bool getMetaKey();
    void setMetaKey(bool metaKey);
    bool getRepeat();
    void setRepeat(bool repeat);
    std::u16string getLocale();
    void setLocale(const std::u16string& locale);
    unsigned int getCharCode();
    void setCharCode(unsigned int charCode);
    unsigned int getKeyCode();
    void setKeyCode(unsigned int keyCode);
    unsigned int getWhich();
    void setWhich(unsigned int which);
    // Object
    virtual Any message_(uint32_t selector, const char* id, int argc, Any* argv)
    {
        return events::KeyboardEventInit::dispatch(this, selector, id, argc, argv);
    }
    static const char* const getMetaData()
    {
        return events::KeyboardEventInit::getMetaData();
    }
};

}
}
}
}

#endif  // ORG_W3C_DOM_BOOTSTRAP_KEYBOARDEVENTINITIMP_H_INCLUDED
