// Generated by esidl (r1752).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "MessageChannelImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

html::MessagePort MessageChannelImp::getPort1()
{
    // TODO: implement me!
    return static_cast<Object*>(0);
}

html::MessagePort MessageChannelImp::getPort2()
{
    // TODO: implement me!
    return static_cast<Object*>(0);
}

}
}
}
}
