// Generated by esidl 0.3.0.
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "MessageEventImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

Any MessageEventImp::getData()
{
    // TODO: implement me!
    return 0;
}

std::u16string MessageEventImp::getOrigin()
{
    // TODO: implement me!
    return u"";
}

std::u16string MessageEventImp::getLastEventId()
{
    // TODO: implement me!
    return u"";
}

html::Window MessageEventImp::getSource()
{
    // TODO: implement me!
    return nullptr;
}

ObjectArray<html::MessagePort> MessageEventImp::getPorts()
{
    // TODO: implement me!
    return ObjectArray<html::MessagePort>();
}

}
}
}
}
