// Generated by esidl (r1752).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "MessageEventImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

Any MessageEventImp::getData()
{
    // TODO: implement me!
    return 0;
}

std::u16string MessageEventImp::getOrigin()
{
    // TODO: implement me!
    return u"";
}

std::u16string MessageEventImp::getLastEventId()
{
    // TODO: implement me!
    return u"";
}

html::Window MessageEventImp::getSource()
{
    // TODO: implement me!
    return static_cast<Object*>(0);
}

ObjectArray<html::MessagePort> MessageEventImp::getPorts()
{
    // TODO: implement me!
    return static_cast<Object*>(0);
}

void MessageEventImp::initMessageEvent(std::u16string typeArg, bool canBubbleArg, bool cancelableArg, Any dataArg, std::u16string originArg, std::u16string lastEventIdArg, html::Window sourceArg, Sequence<html::MessagePort> portsArg)
{
    // TODO: implement me!
}

}
}
}
}
