// Generated by esidl 0.3.0.
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "MessageEventInitImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

Any MessageEventInitImp::getData()
{
    // TODO: implement me!
    return 0;
}

void MessageEventInitImp::setData(Any data)
{
    // TODO: implement me!
}

std::u16string MessageEventInitImp::getOrigin()
{
    // TODO: implement me!
    return u"";
}

void MessageEventInitImp::setOrigin(const std::u16string& origin)
{
    // TODO: implement me!
}

std::u16string MessageEventInitImp::getLastEventId()
{
    // TODO: implement me!
    return u"";
}

void MessageEventInitImp::setLastEventId(const std::u16string& lastEventId)
{
    // TODO: implement me!
}

html::Window MessageEventInitImp::getSource()
{
    // TODO: implement me!
    return nullptr;
}

void MessageEventInitImp::setSource(html::Window source)
{
    // TODO: implement me!
}

ObjectArray<html::MessagePort> MessageEventInitImp::getPorts()
{
    // TODO: implement me!
    return ObjectArray<html::MessagePort>();
}

void MessageEventInitImp::setPorts(ObjectArray<html::MessagePort> ports)
{
    // TODO: implement me!
}

}
}
}
}
