// Generated by esidl 0.3.0.
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "MutationObserverImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

void MutationObserverImp::observe(Node target, events::MutationObserverInit options)
{
    // TODO: implement me!
}

void MutationObserverImp::disconnect()
{
    // TODO: implement me!
}

Sequence<events::MutationRecord> MutationObserverImp::takeRecords()
{
    // TODO: implement me!
    return Sequence<events::MutationRecord>();
}

}
}
}
}
