// Generated by esidl (r1745).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "MutationEventImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

void MutationEventImp::initMutationEvent(std::u16string typeArg, bool canBubbleArg, bool cancelableArg, Object relatedNodeArg, std::u16string prevValueArg, std::u16string newValueArg, std::u16string attrNameArg, unsigned short attrChangeArg)
{
    relatedNode = relatedNodeArg;
    prevValue = prevValueArg;
    newValue = newValueArg;
    attrName = attrNameArg;
    attrChange = attrChangeArg;
    initEvent(typeArg, canBubbleArg, cancelableArg);
}

}
}
}
}
