// Generated by esidl 0.3.0.
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "MutationRecordImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

std::u16string MutationRecordImp::getType()
{
    // TODO: implement me!
    return u"";
}

Node MutationRecordImp::getTarget()
{
    // TODO: implement me!
    return nullptr;
}

NodeList MutationRecordImp::getAddedNodes()
{
    // TODO: implement me!
    return nullptr;
}

NodeList MutationRecordImp::getRemovedNodes()
{
    // TODO: implement me!
    return nullptr;
}

Node MutationRecordImp::getPreviousSibling()
{
    // TODO: implement me!
    return nullptr;
}

Node MutationRecordImp::getNextSibling()
{
    // TODO: implement me!
    return nullptr;
}

Nullable<std::u16string> MutationRecordImp::getAttributeName()
{
    // TODO: implement me!
    return u"";
}

Nullable<std::u16string> MutationRecordImp::getAttributeNamespace()
{
    // TODO: implement me!
    return u"";
}

Nullable<std::u16string> MutationRecordImp::getOldValue()
{
    // TODO: implement me!
    return u"";
}

}
}
}
}
