// Generated by esidl 0.3.0.
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "NavigatorContentUtilsImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

void NavigatorContentUtilsImp::registerProtocolHandler(const std::u16string& scheme, const std::u16string& url, const std::u16string& title)
{
    // TODO: implement me!
}

void NavigatorContentUtilsImp::registerContentHandler(const std::u16string& mimeType, const std::u16string& url, const std::u16string& title)
{
    // TODO: implement me!
}

std::u16string NavigatorContentUtilsImp::isProtocolHandlerRegistered(const std::u16string& scheme, const std::u16string& url)
{
    // TODO: implement me!
    return u"";
}

std::u16string NavigatorContentUtilsImp::isContentHandlerRegistered(const std::u16string& mimeType, const std::u16string& url)
{
    // TODO: implement me!
    return u"";
}

void NavigatorContentUtilsImp::unregisterProtocolHandler(const std::u16string& scheme, const std::u16string& url)
{
    // TODO: implement me!
}

void NavigatorContentUtilsImp::unregisterContentHandler(const std::u16string& mimeType, const std::u16string& url)
{
    // TODO: implement me!
}

}
}
}
}
