// Generated by esidl 0.3.0.
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#ifndef ORG_W3C_DOM_BOOTSTRAP_NAVIGATORIDIMP_H_INCLUDED
#define ORG_W3C_DOM_BOOTSTRAP_NAVIGATORIDIMP_H_INCLUDED

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <org/w3c/dom/html/NavigatorID.h>

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{
class NavigatorIDImp : public ObjectMixin<NavigatorIDImp>
{
public:
    // NavigatorID
    std::u16string getAppName();
    std::u16string getAppVersion();
    std::u16string getPlatform();
    std::u16string getUserAgent();
    // Object
    virtual Any message_(uint32_t selector, const char* id, int argc, Any* argv)
    {
        return html::NavigatorID::dispatch(this, selector, id, argc, argv);
    }
    static const char* const getMetaData()
    {
        return html::NavigatorID::getMetaData();
    }
};

}
}
}
}

#endif  // ORG_W3C_DOM_BOOTSTRAP_NAVIGATORIDIMP_H_INCLUDED
