// Generated by esidl 0.3.0.
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "NavigatorIDImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

std::u16string NavigatorIDImp::getAppName()
{
    // TODO: implement me!
    return u"";
}

std::u16string NavigatorIDImp::getAppVersion()
{
    // TODO: implement me!
    return u"";
}

std::u16string NavigatorIDImp::getPlatform()
{
    // TODO: implement me!
    return u"";
}

std::u16string NavigatorIDImp::getUserAgent()
{
    // TODO: implement me!
    return u"";
}

}
}
}
}
