// Generated by esidl 0.3.0.
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "NodeIteratorImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

Node NodeIteratorImp::getRoot()
{
    // TODO: implement me!
    return nullptr;
}

Node NodeIteratorImp::getReferenceNode()
{
    // TODO: implement me!
    return nullptr;
}

bool NodeIteratorImp::getPointerBeforeReferenceNode()
{
    // TODO: implement me!
    return 0;
}

unsigned int NodeIteratorImp::getWhatToShow()
{
    // TODO: implement me!
    return 0;
}

traversal::NodeFilter NodeIteratorImp::getFilter()
{
    // TODO: implement me!
    return nullptr;
}

Node NodeIteratorImp::nextNode()
{
    // TODO: implement me!
    return nullptr;
}

Node NodeIteratorImp::previousNode()
{
    // TODO: implement me!
    return nullptr;
}

void NodeIteratorImp::detach()
{
    // TODO: implement me!
}

}
}
}
}
