// Generated by esidl 0.3.0.
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "OnErrorEventHandlerNonNullImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

Any OnErrorEventHandlerNonNullImp::operator() (Any event, const std::u16string& source, unsigned int lineno, unsigned int column)
{
    // TODO: implement me!
    return 0;
}

}
}
}
}
