// Generated by esidl 0.2.1.
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "PageTransitionEventImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

bool PageTransitionEventImp::getPersisted()
{
    // TODO: implement me!
    return 0;
}

void PageTransitionEventImp::initPageTransitionEvent(const std::u16string& typeArg, bool canBubbleArg, bool cancelableArg, bool persistedArg)
{
    // TODO: implement me!
}

}
}
}
}
