// Generated by esidl 0.3.0.
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#ifndef ORG_W3C_DOM_BOOTSTRAP_POPSTATEEVENTINITIMP_H_INCLUDED
#define ORG_W3C_DOM_BOOTSTRAP_POPSTATEEVENTINITIMP_H_INCLUDED

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <org/w3c/dom/html/PopStateEventInit.h>
#include "EventInitImp.h"

#include <org/w3c/dom/events/EventInit.h>

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{
class PopStateEventInitImp : public ObjectMixin<PopStateEventInitImp, EventInitImp>
{
public:
    // PopStateEventInit
    Any getState();
    void setState(Any state);
    // Object
    virtual Any message_(uint32_t selector, const char* id, int argc, Any* argv)
    {
        return html::PopStateEventInit::dispatch(this, selector, id, argc, argv);
    }
    static const char* const getMetaData()
    {
        return html::PopStateEventInit::getMetaData();
    }
};

}
}
}
}

#endif  // ORG_W3C_DOM_BOOTSTRAP_POPSTATEEVENTINITIMP_H_INCLUDED
