// Generated by esidl (r1745).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "ProgressEventImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

bool ProgressEventImp::getLengthComputable()
{
    // TODO: implement me!
    return 0;
}

unsigned int ProgressEventImp::getLoaded()
{
    // TODO: implement me!
    return 0;
}

unsigned int ProgressEventImp::getTotal()
{
    // TODO: implement me!
    return 0;
}

void ProgressEventImp::initProgressEvent(std::u16string typeArg, bool canBubbleArg, bool cancelableArg, bool lengthComputableArg, unsigned int loadedArg, unsigned int totalArg)
{
    // TODO: implement me!
}

void ProgressEventImp::initProgressEventNS(std::u16string namespaceURI, std::u16string typeArg, bool canBubbleArg, bool cancelableArg, bool lengthComputableArg, unsigned int loadedArg, unsigned int totalArg)
{
    // TODO: implement me!
}

}
}
}
}
