// Generated by esidl 0.3.0.
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "TrackEventInitImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

Object TrackEventInitImp::getTrack()
{
    // TODO: implement me!
    return static_cast<Object*>(0);
}

void TrackEventInitImp::setTrack(Object track)
{
    // TODO: implement me!
}

}
}
}
}
