// Generated by esidl 0.3.0.
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "UIEventInitImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

bool UIEventInitImp::getBubbles()
{
    // TODO: implement me!
    return 0;
}

void UIEventInitImp::setBubbles(bool bubbles)
{
    // TODO: implement me!
}

bool UIEventInitImp::getCancelable()
{
    // TODO: implement me!
    return 0;
}

void UIEventInitImp::setCancelable(bool cancelable)
{
    // TODO: implement me!
}

html::Window UIEventInitImp::getView()
{
    // TODO: implement me!
    return static_cast<Object*>(0);
}

void UIEventInitImp::setView(html::Window view)
{
    // TODO: implement me!
}

int UIEventInitImp::getDetail()
{
    // TODO: implement me!
    return 0;
}

void UIEventInitImp::setDetail(int detail)
{
    // TODO: implement me!
}

}
}
}
}
