// Generated by esidl (r1745).
// This file is expected to be modified for the Web IDL interface
// implementation.  Permission to use, copy, modify and distribute
// this file in any software license is hereby granted.

#include "WheelEventImp.h"

namespace org
{
namespace w3c
{
namespace dom
{
namespace bootstrap
{

int WheelEventImp::getDeltaX()
{
    // TODO: implement me!
    return 0;
}

int WheelEventImp::getDeltaY()
{
    // TODO: implement me!
    return 0;
}

int WheelEventImp::getDeltaZ()
{
    // TODO: implement me!
    return 0;
}

unsigned int WheelEventImp::getDeltaMode()
{
    // TODO: implement me!
    return 0;
}

void WheelEventImp::initWheelEvent(std::u16string typeArg, bool canBubbleArg, bool cancelableArg, html::Window viewArg, int detailArg, int screenXArg, int screenYArg, int clientXArg, int clientYArg, unsigned short buttonArg, events::EventTarget relatedTargetArg, std::u16string modifiersListArg, int deltaXArg, int deltaYArg, int deltaZArg, unsigned int deltaMode)
{
    // TODO: implement me!
}

}
}
}
}
